mkdocs.yml, overrides/partials/integrations/analytics/amplitude.html
page views to analytics.
Event Name: `page viewed`
Event Properties:
* `url`: the full page url
* `path`: the full url path
* `product` (optional): the first path segment
* `analytics`, `experiment`, `data`, or `resources`
* `page` (optional): the last path segment
* `anchor` (optional): the page anchor
=> add amplitude site analytics integration

docs/experiment/sdks/go-sdk.md, mkdocs.yml
Add documentation for the Experiment Go Server SDK (Beta).
=> Experiment Go Server SDK (Beta)

docs/analytics/sdks/python-sdk.md
Sync up with python dev doc with old site
=> Update python dev doc

docs/data/sources/snowflake.md
Updated snowflake import dev docs
Added examples for event, user, group import.
As soon as possible would be great. Our customer (data robot) is waiting for this.
As soon as possible would be great. Our customer (data robot) is waiting for this.
- Doc update - https://amplitude.atlassian.net/browse/DDI-106
@caseyamp
=> Update snowflake import dev docs

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/doc-improvement.yml, .github/ISSUE_TEMPLATE/site-bug-report.yml, mkdocs.yml, overrides/partials/content.html
Adding a report issue button and issue templates. 
Casual.
=> Updating Issue Reporting

docs/data/sdks/python.md
Added event level groups setting docs and examples
@caseyamp
=> Event level groups attributes

docs/data/sources/snowflake.md
some customers have been adding the whole URL and they are getting an error
@caseyamp
=> additional details about account name

.vscode/extensions.json
Configure Recommended Extensions for `amplitude-dev-center` so users don't have to find the extensions
https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions
N/A
@caseyamp
=> Configure Recommended Extensions for VSCode

overrides/partials/integrations/analytics/amplitude.html
* Fix tracking analytics on navigation after switch to instant load.
Whenever
@caseyamp
=> fix analytics for instant load

overrides/partials/integrations/analytics/amplitude.html
* Enable utm, referrer, and gclid support in analytics
Whenever
@caseyamp
=> enabled utm, referrer, and gclid support in analytics

CONTRIBUTING.md, doc-templates/api-template.md, doc-templates/integration-template.md, doc-templates/sdk-template.md, docs/LICENSE.md
Adding doc templates for folks to use to make creating new docs easier. 
Casual
=> adding doc templates, license and updating contribution guide

docs/analytics/apis/dashboard-rest-api.md
I recently added a new query param to this api, so I'm adding docs for it, and slightly adjusting some of the wording.
Not urgent. This parameter addition was a customer request, so we are notifying them directly.
@caseyamp
=> update /api/2/useractivity to add "direction" query param

docs/data/destinations/bigquery.md
Adding raw event and merged user schemas for BQ Export
Adding raw event and merged user schemas for BQ Export
ASAP
@caseyamp
=> Adding event and MU schemas

docs/data/destinations/redshift.md
Adding Merged User table schema to redshift export
Adding Merged User table schema to redshift export
ASAP 😄 
@caseyamp
=> Adding MU table schema to redshift export

docs/data/sources/qualtrics.md, includes/data-sources-other.md, mkdocs.yml
Adding Qualtrics import docs. 
ASAP
=> Add Qualtrics import docs

docs/data/sdks/typescript-browser.md
Update Typescript SDK for Browser to include more complete and accurate information.
🤔 
@caseyamp
=> Update docs for typescript sdk for browser

docs/experiment/sdks/go-sdk.md
=> experiment-go-server: add note that alpine linux is not supported

docs/experiment/apis/management-api.md, mkdocs.yml
Add experiment management api docs.
ASAP
@caseyamp
=> add experiment management api docs

docs/data/sdks/typescript-browser.md
Adds documentation regarding web attribution in Analytics TS SDK
Earliest convenience
@caseyamp
=> Adds web attribution docs

docs/analytics/apis/dashboard-rest-api.md, mkdocs.yml
fixing a few tickets 
whenever
=> Ticketblitz

docs/data/sdks/react-native-sdk.md, mkdocs.yml
* New SDK doc for next-gen react-native sdk
When the SDK is published. (maybe later this week or early next)
@caseyamp
=> add documentation for next gen react-native SDK

docs/analytics/apis/batch-event-upload-api.md, docs/analytics/apis/export-api.md, docs/analytics/apis/lookup-tables-api.md, docs/analytics/index.md, mkdocs.yml
Add Lookup Table API documentation
No deadline.
=> Add Lookup Table API documentation

docs/experiment/sdks/react-native-sdk-legacy.md, docs/experiment/sdks/react-native-sdk.md, mkdocs.yml
* New SDK doc for experiment React Native v1 SDK.
* This is a major release, so the old docs have been moved under a new `Legacy` directory in the side nav
End of the day.
@caseyamp
=> add experiment react native v1 sdk

docs/data/destinations/netcore-cohort.md, includes/data-destinations-cohorts.md, mkdocs.yml
Adding netcore cohort doc. DDI-188
ASAP
@caseyamp
=> add netcore cloud cohort doc

docs/data/sdks/android.md, docs/data/sdks/flutter.md, docs/data/sdks/ios.md, docs/data/sdks/java.md, docs/data/sdks/javascript.md, docs/data/sdks/node.md, docs/data/sdks/react-native-sdk.md, docs/data/sdks/react-native.md, docs/data/sdks/typescript-browser.md, docs/data/sdks/unity.md, docs/data/sdks/unreal.md, includes/sdk-httpv2-notice.md
Adding note about event requirements to SDKS. 
Soon.
=> add http v2 notice to SDKs

docs/data/destinations/userflow-cohort.md, includes/data-destinations-cohorts.md, mkdocs.yml
Adding userflow cohort docs
ASAP
=> Add userflow docs

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/general/performance-and-caching.md
add another benchmarking row and update the other table.
asap
@caseyamp
=> add jvm local evaluation benchmarks

docs/experiment/sdks/go-sdk.md
=> remove notice of memory leak in golang sdk

docs/data/sources/intercom.md
=> add intercom webhook link

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/guides/create-local-evaluation-flag.md, docs/experiment/index.md, docs/experiment/sdks/go-sdk.md, docs/experiment/sdks/jvm-sdk.md, docs/experiment/sdks/nodejs-sdk.md, mkdocs.yml
Get ready for local evaluation GA
When we release local evaluation to GA
@caseyamp
=> remove references to alpha; update nodejs docs

mkdocs.yml
Adding analytics SDK catalog to nav
Casual
=> Add SDKs to analytics nav

docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md
Adds destination plugin example for typescript browesr
@caseyamp
=> Amp 57991 plugin example

docs/analytics/apis/taxonomy-api.md
* `category` -> `event-type`
@caseyamp
=> Small Fixes to Taxonomy API Docs

docs/data/sdks/react-native-sdk.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md
Adds flush, add and remove methods
@caseyamp
=> Adds flush, add and remove methods

docs/analytics/apis/group-identify-api.md
Clarify group limit. 
ASAP
@caseyamp
=> Update Group Types Limit Fixes #184

overrides/partials/integrations/analytics/amplitude.html
- Set user id and device id if they are found from other amplitude cookies under "amplitude.com" domain
@caseyamp
=> Add tracking authenticated user support

docs/experiment/sdks/python-sdk.md
- add Experiment Python local evaluation
@caseyamp
=> doc: add experiment python local evaluation support

docs/data/sdks/react-native-sdk.md
Adds docs for `adid` tracking option
Earliest convenence
@caseyamp
=> Add docs for adid tracking option

overrides/partials/integrations/analytics/amplitude.html
=> Break the loop if user id is found

docs/data/sdks/react-native-sdk.md, docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/react-native-sdk-legacy.md, docs/experiment/sdks/react-native-sdk.md
- docs: add adid to rn and update experiment ios integration
@caseyamp
=> docs: add adid to rn and update experiment ios integration

docs/data/sdks/android-kotlin/index.md
fix android sdk example error
@caseyamp
=> fix android sdk example

docs/data/sources/amazon-s3.md
Clarified how to use the example IAM policy. 
Casual
=> Clarify IAM policy

docs/experiment/sdks/python-sdk.md
Clean up the doc
N/A
@caseyamp
=> doc: experiment python doc clean up

docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/react-native-sdk-legacy.md, docs/experiment/sdks/react-native-sdk.md
Experiment SDK instanceName is case sensitive. Analytics SDK instanceName is case insensitive. 
- [ x Doc update.
@caseyamp
=> Update experiment SDK instanceName description

docs/analytics/apis/user-profile-api.md, docs/data/destinations/airship-cohort.md, docs/data/destinations/google-ads-cohort.md, docs/data/destinations/marketing-cloud-cohort.md, docs/data/sources/segment.md, vale/styles/Amplitude/Headings.yml
=> Change Recommend to Audiences

docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/google-analytics-4.md, docs/data/destinations/google-pub-sub.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md, docs/data/destinations/kinesis-data-stream.md, docs/data/destinations/kinesis-firehose.md, docs/data/destinations/meta-pixel.md
Change Event Streaming integration release statuses
August 22
=> MERGE AUG 22 Move event streaming integration release statuses

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/python-sdk.md, docs/experiment/sdks/ruby-sdk.md
=> feat: ruby local evaluation docs

mkdocs.yml
Configuring new features for Insiders upgrade 
Whenever
=> Added page status extra config

docs/data/sdks/typescript-browser/index.md
Fixed typos in typescript sdk docs
@caseyamp
=> Fix typos and grammar in TS SDK docs

docs/data/ampli/migration.md
Add considerations for migration
Casual.
=> Add considerations for migration doc

docs/data/deprecated-sdks/nodejs.md, docs/data/sdks/java/ampli.md, docs/data/sdks/unity/index.md, docs/experiment/general/performance-and-caching.md
Fixes a bunch of log errors and broken links 
Whenever
=> Adds various fixes for log warnings

docs/data/sdks/react-native/index.md
=> docs: add new functions to rn

.github/pull_request_template.md, .markdownlintignore, docs/stylesheets/extra.css, formatting-cheatsheet.md
Add Deprecation notice admonition type + meta docs. 
ASAP
=> DDI-209 Add Deprecation Admonition

docs/data/ampli/middleware.md
=> DDI-211 Fix broken plugin link

.github/workflows/mega-linter.yml, .markdown-link-check.json, .markdownlint.json, .mega-linter.yml, docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/android/ampli.md, docs/data/sdks/android/index.md, docs/data/sdks/ios/ampli.md, docs/data/sdks/javascript/ampli.md, docs/data/sdks/javascript/index.md, docs/data/sdks/node/index.md, docs/data/sdks/python/ampli.md, docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-browser/ampli.md
Upgrade megalinter version. Tweak configs and fix more links that surfaced. 
ASAP
=> Upgrades to new version of megalinter

docs/data/sdks/android-kotlin/index.md
=> kotlin doc fix

mkdocs.yml
Improvements to syntax highlighting. 
Casual
=> DDI-213 Testing Pygments theming overrides

mkdocs.yml
Undoes the highlighting changes made earlier today due to erratic behavior. 
ASAP
=> Reverses highlighting changes made earlier

docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/ampli.md, docs/data/sdks/typescript-react-native/index.md, mkdocs.yml
* added Ampli RN v2 docs
@caseyamp
=> AMP-59348 added Ampli RN v2 docs

docs/data/destinations/amazon-s3.md, docs/data/destinations/bigquery.md, docs/data/destinations/google-cloud-storage.md, docs/data/destinations/snowflake.md, docs/data/sources/amazon-s3.md, docs/data/sources/bigquery.md, docs/data/sources/google-cloud-storage.md, docs/data/sources/snowflake.md, includes/editions-all-editions.md
Adding all plans reusable and updating warehouse and cloud docs for free plans
. 
ASAP
=> DDI-216 Update Plan Availability for Warehouse and Cloud source/destinations

docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md
Fixes code sample for EU data residency init
@caseyamp
=> Fixes code sample for EU data residency init

docs/data/destinations/bigquery.md
Add a perm to Big Query export doc. 
ASAP
@caseyamp
=> DDI-201 Add permission to custom role prereq

docs/data/destinations/google-pub-sub.md
Small nit fixes to our [Pub/Sub docs](https://www.docs.developers.amplitude.com/data/destinations/google-pub-sub/#considerations)
Not urgent
@caseyamp
=> Google Pub/Sub typo nit

.github/workflows/mega-linter.yml
Change megalinter config to only run on changed or new files instead of all of them every time. 
ASAP
=> DDI-219 change VALIDATE_ALL_CODEBASE to false Megalinter.

.github/styles/Vocab/dev/accept.txt, docs/data/destinations/sendgrid-cohort.md, includes/data-destinations-cohorts.md, mkdocs.yml
Add Sendgrid cohort doc. 
By sept 16
=> DDI-217 Add SendGrid Cohort doc

docs/data/sources.md
Add link to quickstart guide to sources overview
ASAP
=> DDI-227 add link to getting started guide

docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/android-kotlin/index.md
- Add amplitude client reference for android
- Fix for Android Ampli code format
@caseyamp
[DXOC-188]: https://amplitude.atlassian.net/browse/DXOC-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DXOC-188 fix android Amplitude reference and code formats in ampli

docs/data/destinations/marketo-cohort.md
Update marketo cohort doc to reflect reality. 
ASAP
@caseyamp
=> DDI-243 update considerations to reflect app changes"

docs/data/sdks/index.md
=> Quick guide fix

docs/data/ttl-configuration.md
Adding a doc page for TTL (data retention)
ASAP 😄 
@caseyamp
=> adding ttl documentation for dev

docs/data/sdks/go/ampli.md, mkdocs.yml
=> add go ampli doc

docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/ampli.md, docs/data/sdks/android/index.md, docs/data/sdks/flutter/index.md, docs/data/sdks/go/ampli.md, docs/data/sdks/go/index.md, docs/data/sdks/ios/ampli.md, docs/data/sdks/ios/index.md, docs/data/sdks/java/ampli.md, docs/data/sdks/java/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/node/ampli.md, docs/data/sdks/node/index.md, docs/data/sdks/python/ampli.md, docs/data/sdks/python/index.md, docs/data/sdks/typescript-browser/ampli.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/ampli.md, docs/data/sdks/typescript-react-native/index.md, docs/data/sdks/unity/index.md, docs/data/sdks/unreal/index.md, mkdocs.yml
* Go doc updates for latest changes
* Go Ampli docs
@caseyamp
=> Amp 58497 go ampli developer doc

docs/data/sources/optimizely.md
=> DDI-247 Fix broken link

includes/postman.md
Fixes "Run In Postman" button opening in a lightbox issue that was apparently introduced when I turned on glightbox plugin.
ASAP
=> Disables lightboxing on a button that is actually an image

docs/data/sources/cordial.md, includes/data-sources-other.md, mkdocs.yml
Adds Cordial Event import docs. 
ASAP
=> Add Cordial Event Docs

mkdocs.yml, requirements.txt
Upgrading Material version and implementing new tab features. 
Whenever
Tested in Dev.
=> Ddi 248.test new version

insiders.mkdocs.yml, mkdocs.yml
Accidentally added an insiders-only feature to configs used by non-insiders, causing build failures. 
ASAP
=> Fixing config file error

docs/data/sources/lookup-table.md
Update feature availability for lookup table beta.  
ASAP
=> Fix feature availability note

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md
=> AMP-59355 - add kotlin advanced topic

docs/data/sources/amazon-s3.md
Update on S3 import file prefix requirement to avoid confusion
@caseyamp
=> Update on S3 import file prefix requirement

docs/analytics/apis/dashboard-rest-api.md
=> Fixes #319 JSON problem

docs/experiment/sdks/javascript-sdk.md
=> update the expeirment js sdk script tag snippet to include init

.github/styles/Amplitude/Will.yml, .github/styles/Vocab/dev/accept.txt, docs/data/sdks/marketing-analytics-browser/index.md, includes/sdk-ts-browser/marketing-analytics.md, includes/sdk-ts-browser/shared-configurations.md
Fixing some things in the Marketing Analytics SDK
ASAP
=> Fixing some errors in MA SDK

docs/data/sdks/android-kotlin/index.md
Adds example for setting min_id_length
@caseyamp
=> Adds example for setting min_id_length

docs/analytics/apis/taxonomy-api.md
=> Fix response type for get event type

.github/styles/Vocab/dev/accept.txt, docs/data/destinations/statsig.md, includes/data-destinations-event-streaming.md, mkdocs.yml
Adds the Statsig Event Streaming Docs
ASAP
=> Adds Statsig docs

docs/data/destinations/statsig-cohort.md
=> Add new button to statsig

docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/react-native-sdk.md
=> add clear variants doc

docs/data/sdks/flutter/index.md
=> Add flutter compatibility matrix

.github/styles/Amplitude/Will.yml, .github/styles/Vocab/dev/accept.txt, docs/data/ampli/git-workflow.md, docs/data/deprecated-sdks/android.md, docs/data/deprecated-sdks/browser.md, docs/data/deprecated-sdks/dotnet.md, docs/data/deprecated-sdks/ios.md, docs/data/deprecated-sdks/jre-v3.md, docs/data/deprecated-sdks/jre.md, docs/data/deprecated-sdks/nodejs.md, docs/data/deprecated-sdks/python.md, docs/data/deprecated-sdks/ruby-v2.md, docs/data/deprecated-sdks/ruby.md
Just a couple of little Vale rule tweaks.
=> Vale Rule Tweaks 

docs/data/sources/moengage.md, includes/data-sources-other.md, mkdocs.yml
Adds MoEngage event import docs. 
ASAP
=> Add MoEnage Events

.github/styles/Amplitude/HeadingGerunds.yml, docs/analytics/apis/dashboard-rest-api.md
Add findable info about downloading data tables info. 
ASAP
=> Add searchable section for Data Tables export.

docs/data/destinations.md, docs/data/sdks/android-kotlin/index.md, docs/data/sdks/flutter/index.md, docs/partners/index.md, docs/partners/sending-cohorts.md
Final Vale Warning / Error Fixes!
=> Vale Cleanup: Final warning and error fixes. 

docs/data/destinations/redshift.md
=> Remove Beta Label

docs/data/destinations/snowflake.md
Fixes broken admontion formatting.
=> Fix broken admonition syntax

docs/data/converter-configuration-reference.md
Fix bad documentation on group identifies.
ASAP
@caseyamp
=> Fix $groupIdentify -> $groupidentify.

docs/data/sdks/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, mkdocs.yml
Restructures Browser SDK section/ renames TypeScript Browser SDK.
=> browser sdks re-structure

.github/styles/Amplitude/HeadingGerunds.yml, .github/styles/Amplitude/Headings.yml, .github/styles/Vocab/dev/accept.txt, docs/data/destinations/webhooks-streaming.md, includes/data-destinations-event-streaming.md, mkdocs.yml
=> DDI-269 Add Webhook Doc

.github/styles/Amplitude/Headings.yml, docs/data/destinations/snowflake-data-share.md, includes/data-destinations-warehouse.md, mkdocs.yml
New doc for Snowflake Data Share Export
(I know I always say this but) ASAP :)
@caseyamp
=> snowflake data share export documentation

docs/data/destinations/lantern-event-streaming.md, includes/data-destinations-event-streaming.md, mkdocs.yml, overrides/.icons/lantern.svg
=> DDI-260 Add Lantern Docs

docs/data/destinations/maze-cohort.md
=> Fixing desc and status for maze doc

docs/data/destinations/redshift.md
Add Redshift Amplitude IPs allowlisting instructions 
ASAP
=> DDI-273 Adding Allowlisting instructions for redshift

docs/data/sdks/ios/index.md
=> fix code alignment

docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/android/ampli.md, docs/data/sdks/ios/ampli.md, docs/data/sdks/java/ampli.md, docs/data/sdks/javascript/ampli.md, docs/data/sdks/node/ampli.md, docs/data/sdks/python/ampli.md, docs/data/sdks/react-native/ampli.md, docs/data/sdks/typescript-browser/ampli.md, docs/data/sdks/typescript-node/ampli.md
Clean up implementation page mentioned in ampli instructions
@caseyamp
=> clean up implementation page link

docs/data/sdks/react-native/index.md
=> remove the description not applied

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/node/index.md, docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-node/index.md
=> DDI-276 Fixes Broken Link + Search Tweaks for SDKs

docs/data/sources/kochava.md
=> DDI-280 Fixing Link

mkdocs.yml, overrides/main.html
=> DDI-278 Adds Hackathon banner and turns on dismiss feature

docs/data/destinations/bigquery.md
Adds considerations for BQ doc. 
ASAP
=> DDI-275 Adding considerations section for BQ export

overrides/main.html
=> Update link to hackathon

docs/data/index.md
=> Remove Data beta label

docs/data/sources/salesforce-group.md
Add note about SF Sandboxes 
ASAP
=> DDI-279 Add Sandbox Note

docs/analytics/apis/dashboard-rest-api.md
Fixing bracket notation error 
ASAP
=> DDI-288 Fixing bracket syntax error

docs/data/sdks/typescript-browser/ampli.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/ampli.md, docs/data/sdks/typescript-react-native/index.md
This PR updates the TS SDKs docs:
- how to override sdk configuration with ampli load
- add custom http client guidance section
- async flow control of flush and track
@caseyamp
=> docs: update ts docs

docs/experiment/sdks/react-native-sdk.md
Broken link reported via Slack.
=> Fixing broken link

requirements.txt
Updates Pillow requirement to fix vulnerability.
=> DDI-291 update Pillow req for vulnerability

docs/analytics/apis/taxonomy-api-2.md
Taxonomy API 2.0 update.
@caseyamp
=> AMP-63782 GraphQL Taxonomy API 2.0 concept edits 1

docs/data/destinations/userlist-event-streaming.md, includes/data-destinations-event-streaming.md, mkdocs.yml
Adding Userlist Event Streaming docs. 
By end of Nov.
=> DDI-262 add Userlist Even Streaming doc

docs/data/sdks/typescript-browser/migration.md
Quick lil formatting fix + minor tweak to OrgId in examples. 
🤷
=> DDI-298 Clarifying example and fixing broken formatting

overrides/main.html
Removes london hackathon banner.
=> DDI-283 Removing hackathon banner

.github/styles/Amplitude/ComplexWords.yml, .github/styles/Amplitude/HeadingGerunds.yml, .github/styles/Amplitude/Headings.yml, .github/styles/Amplitude/Passive.yml, docs/analytics/apis/taxonomy-api-2.md, docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/ampli.md, docs/data/sdks/android/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-browser/index.md, docs/experiment/apis/evaluation-api.md, docs/experiment/apis/management-api.md, docs/experiment/general/evaluation/implementation.md
More tiny interstitial tweaks.
=> Vale Tweaks Nov 28

docs/data/sdks/marketing-analytics-browser/index.md
Fix invalid name in Configuration
No deadline 
@caseyamp
=> Fix invalid name in Configuration

docs/analytics/apis/user-privacy-api.md
Adds note about authorization when using cURL
ASAP
=> AMP-63922 Adding base64 note

docs/data/ampli/git-workflow.md
=> Fix visible comment

overrides/home.html
Got some PS feedback that highlighted that folks expected something different from the doc IA given the features on the home page. Those were never meant to be permanent and I didn't get any solid feedback for them before we launched. I went ahead and updated them to align more with what we say about these products on the Help Center.
=> DDI-305 Make Tweaks to home page. 

docs/analytics/apis/dashboard-rest-api.md, docs/stylesheets/extra.css, includes/postman-interactive.md
Now that the docs are more stable, we should experiment with adding more examples in the docs themselves. This PR should serve as a experiment for adding these examples. We have a few options as far as IA and formatting are concerned. 
No deadline yet
=> DDI-303 Add examples to API doc (experimental) 

docs/experiment/sdks/react-native-sdk.md, mkdocs.yml
GA react native SDK v1.0.0
@caseyamp
=> remove beta tags from experiment react native sdk

docs/data/sdks/flutter/index.md
=> feat: add flutter setDeviceId doc

docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-node/index.md, mkdocs.yml
=> feat: GA node and ampli node

docs/experiment/sdks/ruby-sdk.md, mkdocs.yml
GA Experiment Ruby SDK
N/A
@caseyamp
=> doc: GA experiment ruby SDK

requirements.txt
GitPython has a security flaw. It's in our requirements.txt but I'm not sure what it belongs to. Went through and removed all unused packages, and added comments to explain what each set of packages is for. Tested in dev. 
Fixes https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/security/dependabot/4
ASAP
=> DDI-333 Clean up requirements.txt

docs/data/destinations/bigquery.md
=> BigQuery integrity check information

docs/analytics/apis/chart-annotations-api.md
Need to clarify auth in the examples. 
Whenever
=> DDI-331 Investigate Auth confusion in Annotations API doc. 

docs/data/sources/google-tag-manager.md
Adds a new GTM template
ASAP
@caseyamp
=> DDI-335 Adding new GTM template

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md, mkdocs.yml
=> doc: add ios swift sdk

includes/data-sources-sdks.md
Adds new Beta SDK to catalog
ASAP
=> Add IOS swift beta sdk to sdk catalog

docs/data/sources/insider.md, includes/data-sources-other.md, mkdocs.yml
Adds Insider event import docs. 
Soon
=> DDI-308 Import Insider Events

docs/experiment/sdks/go-sdk.md, mkdocs.yml
GA Experiment Go SDK
N/A
@caseyamp
=> AMP-66375 GA Experiment Go SDK

docs/all-resources.md, mkdocs.yml, overrides/partials/footer.html
Add links to product updates page in a few places. 
Whenever
=> DDI-328 Add product updates links to pages

docs/data/sources/intercom.md
Add a sentence to describe the behavior 
When do these changes need to be live on the site? 
No hard timeline, but prefer to be updated for the customer.
@caseyamp
=> Update Intercom Dev Doc for Intercom Source v2

docs/data/event-streaming-home.md
Add considerations section to event streaming overview page with notes on limitations for event streaming.
@caseyamp
=> AMP-65499 Add general considerations to event streaming overview

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/python-sdk.md, mkdocs.yml
GA Experiment Python SDK
N/A
@caseyamp
[AMP-52688]: https://amplitude.atlassian.net/browse/AMP-52688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: GA Experiment Python SDK

docs/data/destinations/marketo-cohort.md
Update to reflect this option:
@caseyamp
=> Update Marketo doc to include upsert leads toggle

docs/analytics/apis/ccpa-dsar-api.md
Adds examples to the doc. 
Whenever
=> DDI-348 Add Examples to CCPA DSAR API doc

docs/stylesheets/extra.css, insiders.local.build.yml, insiders.mkdocs.yml, mkdocs.yml, overrides/partials/content.html
Upgrade material to Version 9+
=> DDI-363 Upgrade Material Version

docs/data/destinations/sendgrid-cohort.md
- reword some points and slight refactor
- add new consideration
@caseyamp
=> Update SendGrid cohort export docs

.github/styles/Vocab/dev/accept.txt, docs/changelog.md, mkdocs.yml
Adds a docs changelog
Whenever
=> DDI-362: Adds changelog and all the fixins'

.markdown-link-check.json, linkcheck.sh
Made changes to link linter config file to hopefully stop flagging links wrong and also added a bash script for running the link checker on a single file in terminal  to make it slightly less verbose and therefore, easier to use. 
ASAP to calm down megalinter
=> DDI-366 Make local link checking easier and less stupid

mkdocs.yml
Enables new breadcrumb feature and adds explanatory comments to some settings in config file.
=> DDI-375 Enables Breadcrumb nav and  adds comments to config file

includes/ampli/flush/ampli-flush-snippet-typescript.md
remove extra async flush example
@caseyamp
=> AMP-67032 remove extra async flush example

docs/data/destination-cloud-storage-overview.md, mkdocs.yml
To maximize benefit from breadcrumbs and orient beginner users, add a Cloud storage destination overview . 
Casual
=> DDI-374: Add Cloud Storage Overview

docs/data/source-cloud-storage-overview.md, mkdocs.yml
Adds overview file for Sources: Cloud Storage. Aims to improve breadcrumb nav experience and orient new and casual users. 
Casual
=> DDI-370: Adding Source Cloud storage overview

docs/data/source-other-overview.md, mkdocs.yml
Adds Other Sources overview doc to improve breadcrumb nav experience and orient new or causal users. 
Casual
@caseyamp
=> DDI-368: Adding other sources overview doc

docs/analytics/apis/export-api.md
Adding example blocks in the doc and clarifying some stuff about timezones.
Whenever
=> DDI-350: Export API : Add Examples

docs/partners/integration-portal.md
- Update UI description to reflect current state
@caseyamp
=> Update integration portal docs to reflect UI

docs/data/destinations/snowflake.md, docs/data/sources/snowflake.md
Adds allowlist IPs to a snowflake doc and fixes wonky formatting in another. 
ASAP
=> DDI-388 Fix and add allowlist IPs

docs/analytics/apis/event-streaming-metrics-summary-api.md, includes/api-table-analytics.md, mkdocs.yml
Adds doc for the Event Streaming Metrics API
Soon
=> DDI-381: Adding Metrics API doc

docs/changelog.md
Adding things I missed and things merged after launch.
=> Changelist stragglers

docs/analytics/apis/event-streaming-metrics-summary-api.md
Changed 400 to 500 since that's the status actually returned. 
ASAP
=> DDI-393: Update status for requests outside of 90 day retention period. 

docs/data/sdks/ios-swift/migration.md, docs/data/sdks/ios/index.md, mkdocs.yml
The migration guide from iOS legacy to new iOS SDK
@caseyamp
=> iOS migration

docs/analytics/apis/batch-event-upload-api.md
Minor tweaks and improvements. 
ASAP
=> DDI-346 Link fixes and minor tweaks

docs/all-resources.md, docs/changelog.md, docs/data/sdks/android/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md, mkdocs.yml
Adds utms to links to the community page.
=> DDI-380: Adds UTM params to all community links

docs/data/sdks/android-kotlin/index.md
And the words where we recommend initializing the android SDK.
https://discourse.amplitude.com/t/android-sdk-initialization-clarification/5444/7 
@caseyamp
=> Android init

docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/go/ampli.md, docs/data/sdks/typescript-browser/ampli.md, docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-react-native/ampli.md
=> fix the setGroup ampli call

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/jvm-sdk.md, mkdocs.yml
=> remove beta tags from exp jvm sdk

docs/data/destination-warehouse-overview.md, mkdocs.yml
Adds warehouse overview doc for future expansion and breadcrumb nav. 
ASAP
=> DDI-372 Adds warehouse overview doc

docs/analytics/apis/dashboard-rest-api.md
Fixes a bad endpoint in a code example. 
Ship ASAP
=> DDI-391 Fix incorrect endpoint URL

docs/data/destinations/productboard-cohort.md
=> AMP-66433 change productboard cohort sync description

docs/data/destinations.md, docs/data/sources.md
Adds links to overviews from the main source and destination pages. 
🤷
=> DDI-379 Add links to specific overview pages

.github/styles/Vocab/dev/accept.txt, docs/data/destinations/marketo-cohort.md, docs/data/destinations/marketo-static-list-cohort.md, includes/data-destinations-cohorts.md, mkdocs.yml
Adds the docs for the Marketo Static List integration. 
🤷 
@caseyamp
=> DDI-420 Adding Marketo Static List Docs

docs/data/sdks/ios/index.md
=> added the missed example in ios legacy

docs/data/sdks/sdk-quickstart.md
- add `flush` call in quick start example
@caseyamp
=> doc: update python quick start example with flush

docs/analytics/apis/http-v2-api.md
Add new format API examples to HTTP V2 doc
ASAP
=> DDI-352 Add HTTP V2 Examples

README.md, insiders.local.build.yml, mkdocs.yml, requirements.txt
=> Clean up readme and add comments in config files

docs/analytics/apis/behavioral-cohorts-api.md, docs/analytics/apis/http-v2-api.md
Adds new format examples to cohort api
ASAP
=> DDI-347 Adding New Format Examples to Cohort API

docs/changelog.md
=> DDI-423: Adding Changelog for Feb 5

docs/data/sdks/ios/index.md
* Added docs for identify batching and setIdentifyUploadPeriodSeconds
* Added "Configuration" section covering all configuration options
* https://amplitude.atlassian.net/browse/AMP-68716
=> AMP-68716 add docs for identify batching and configuration

docs/changelog.md
Updating the changelog for this week. 
Adios and godspeed you, my beloved dev docs site. ✌️
=> Casey's Final PR: Updating Changelog

docs/analytics/index.md, docs/data/index.md, docs/documentation-home.md
Change “Instrument Analytics” to "Set up Analytics" to be more friendly to new users
- [] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
=> DDI 416 [Contextual Doc] Amplitude Analytics Overview

docs/analytics/apis/taxonomy-api.md
Adding a note in our Taxonomy API docs for customers to reach out to their CSM or support team to inquire about access.
ASAP
=> Add note for taxonomy api

docs/analytics/plan-your-set-up.md, mkdocs.yml
preview: https://pr-599.d19s7xzcva2mw3.amplifyapp.com/analytics/plan-your-set-up/
This is the second step of our new onboarding process after What is Amplitude page which gives new users a high level overview of what Amplitude is. This page lists out high level steps on how to get started, necessary technical considerations to make, and what events to track upfront.
=> DDI 406 [Contextual Doc] Plan your set up

docs/data/debugger.md
Create another PR for https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/600 which is stuck on AWS Amplify Console Web Preview Expected — Waiting for status to be reported. 
=> DDI 414 [Contextual Doc] Debugging Article

docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md
We are adjusting user forwarding feature so updating the descriptions
@caseyamp
=> AMP-66640 [streaming] Update identify forwarding description

docs/data/sdks/ios-swift/index.md
* Lint fixes for Swift SDK docs - https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/618
=> chore: AMP-69957 lint fixes for Swift SDK docs page

docs/guides/segment-migration-guide.md
=> AMP-69336 Make identify example concise

docs/data/destinations/appsflyer.md, docs/data/destinations/branch.md, docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/google-ads-event-streaming.md, docs/data/destinations/google-analytics-4-firebase.md, docs/data/destinations/google-analytics-4-gtag.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md, docs/data/destinations/meta-pixel.md, includes/data-destinations-event-streaming.md, mkdocs.yml
Adding Branch event streaming docs and slight tweak to other docs
asap
- [ X ] New documentation.
- [ X ] My documentation follows the style guidelines of this project.
- [ X ] I previewed my documentation on a local server using `mkdocs serve`.
- [ X ] Running `mkdocs serve` didn't generate any failures.
- [ X ] I have performed a self-review of my own documentation.
=> AMP-57876 [streaming] Branch streaming docs

docs/experiment/general/exposure-tracking.md
Clarify experiment exposure event billing
=> clarify experiment exposure event billing

docs/analytics/plan-your-set-up.md
preview: https://pr-630.d19s7xzcva2mw3.amplifyapp.com/analytics/plan-your-set-up/
Applied feedback from academy team. 
=> DDI 406 [Contextual Doc] Plan your set up - feedback update

docs/guides/index.md, docs/guides/mParticle-migration-guide.md, docs/guides/segment-migration-guide.md
mParticle to Amplitude CDP migration guide. I couldn't find links to groups & Data equivalent concepts in mParticle. I will update as soon as I find them. Starting PR for any early comments.
as soon as possible.
- [ X] New documentation.
Couldn't get local mkdocs, will check the PR build to verify.
=> AMP-69937 mParticle migration guide.

docs/analytics/apis/scim-api.md
Update limitation to reflect behavior
=> update documentation to recognize page size

docs/data/debugger.md
=> DDI 409 [Contextual Doc] In-app Navigation - data

docs/analytics/apis/taxonomy-import-api.md
=> AMP-70721 taxonomy import api draft

docs/data/sdks/ios-swift/index.md
=> swift doc fix

docs/data/sdks/flutter/index.md, docs/data/sdks/go/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/java/index.md, docs/data/sdks/python/index.md, docs/data/sdks/unity/index.md
=> add default configs for flutter go python and unity

docs/data/sdks/typescript-browser/index.md
`defaultEvents` to `defaultTracking`
=> Fix DET docs for config name

docs/guides/mParticle-migration-guide.md, docs/guides/segment-migration-guide.md
=> AMP-69937 addressing comments on migration guides

mkdocs.yml
https://amplitude.slack.com/archives/C02T742UUMC/p1680126641664929
Re-order left nav destinations alphabetically.
=> order destinations in left nav alphabetically

docs/data/destinations/webhooks-streaming.md
Updated Webhook streaming docs to include user forwarding and to match new docs
=> Update webhook streaming docs

docs/data/destinations/marketo-cohort.md, docs/data/sdks/sdk-quickstart.md
Minor copy update see slack thread
https://amplitude.slack.com/archives/C02T742UUMC/p1680268338521149
No strict deadline
- [X ] I have performed a self-review of my own documentation.
=> Amp 0 fix copy

docs/experiment/general/data-model.md, docs/experiment/guides/getting-started/create-a-deployment.md, docs/guides/amplitude-keys-guide.md
=> dont mix between api key and deployment key

docs/experiment/apis/management-api.md
=> Add how to find the management API Key

docs/data/sources/intercom.md
we're upgrading the Intercom source. Want to provide some information customers can refer to
=> add table of changing event names

docs/data/destinations/customerio.md
add step for choosing account region
=> Customer.io streaming EU availability update

docs/data/sources/snowflake.md
=> AMP-69291 warn users of prop sync limitations for DWH

docs/data/sdks/flutter/index.md
* added setEventUploadPeriodMillis() to Flutter docs 
=> chore: AMP-72827 add Flutter docs for setEventUploadPeriodMillis()

docs/data/sdks/flutter/index.md
Improvement based on Alan's feedback https://discourse.amplitude.com/t/needing-web-session-tracking-that-supports-the-flutter-sdk-and-wants-to-know-timeline-to-accommodate-this-request/10066/6?u=alyssa_yu.
=> improve flutter web doc

docs/data/ampli/middleware.md
https://pr-705.d19s7xzcva2mw3.amplifyapp.com/data/ampli/middleware/
=> more content for middleware

docs/data/sdks/java/index.md
=>  add set event level group in java

docs/data/ampli/plugin.md
- Adds new section to Plugin docs regarding how to forward events to Hotjar
Important, not urgent
=> AMP-71142 Hotjar plugin docs

docs/data/sources/bigquery.md, includes/data-sources-warehouse.md, mkdocs.yml
1. Making the BigQuery import doc visible
2. Adding in examples for event, user property and group property import
As soon as possible
=> AMP-72740 [BigQueryImport] Improve BigQuery import doc

docs/data/sources/amazon-s3.md
=> Updated docs to include Groups format in converter

docs/data/destinations/amazon-s3.md
Update the developer doc for S3 Export to include a section for updating bucket policy to use KMS encryption.
By the end of April
=> AMP-74269 [S3Export] Update the doc to include updating bucket Policy to use KMS encryption

docs/data/sdks/ios/index.md
=> Update to include Experiment integration warning

docs/guides/accounts-instrumentation-guide.md
=> Remove events method from user-level groups

docs/data/sdks/ios-swift/index.md
Customer implemented this only to find out Experiment needed to be implemented separately + no clear timeline for Exp support
=> Update docs to note Experiment is not supported

docs/analytics/apis/batch-event-upload-api.md
=> Remove incorrect 15 minute SLA from batch api doc

docs/data/sdks/typescript-react-native/index.md, includes/sdk-ts-browser/shared-configurations.md
=> fix: add missing config in next gen rn

docs/data/sdks/android/index.md
Fixing description of "trackingSessionEvents" config option, which previously was incorrect
Fixing description of "trackingSessionEvents" config option
ASAP
- [ X] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
=> Update Configuration Options "trackingSessionEvents"

docs/data/sdks/android-kotlin/index.md
https://amplitude.atlassian.net/browse/DXOC-823
* update Kotlin docs to describe how to send a BaseEvent via track
=> fix: DXOC-823 update Kotlin docs to describe how to send a BaseEvent via track

docs/data/sdks/python/index.md
There was a small error in the example code snippet
None
=> Fixed error in example code

docs/data/destinations/hubspot-event-streaming.md
Update HubSpot Event Streaming documentation align with backend change.
=> AMP-77014 Update HubSpot Streaming connector

docs/data/sources/google-tag-manager-client.md
=> fix: fix nits

docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/sdk-architecture.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/sdk-ts/shared-ts-configuration.md
Related to https://amplitude.atlassian.net/browse/AMP-77110
Correct the default type for storageProvider.
=> storage provider fix

docs/data/destinations/google-ads-cohort.md
- Updated google ads cohorts doc with expected match times
=> AMP-72965: Update google ads doc with expected match time

docs/data/sdks/browser-2/index.md, overrides/partials/content.html, overrides/partials/integrations/analytics/amplitude.html
Upgrades instrumentation to Browser SDK 2.0
ASAP
=> Upgrades instrumentation to Browser SDK 2.0

docs/data/sources/google-tag-manager-client.md
related to the [gtm pr](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/pull/16#issuecomment-1590625244). 
=> fix: fix the type based on gtm pr

includes/sdk-ts-browser/tracking-an-event.md
=> track example of passing event obj

includes/ampli/pages/ampli-overview.md
add information on how to configure Amplitude SDK from Ampli
=> fix: add information on how to configure Amplitude SDK from Ampli

docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/google-analytics-4-firebase.md, docs/data/destinations/google-analytics-4-gtag.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md
Updating docs to include warning about identify forwarding volumes
=> AMP-78162 add warning to docs for identify volumes

docs/data/sdks/browser-2/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/sdk-tracking-events-to-multiple-projects.md, includes/sdk-ts/shared-ts-configuration.md
This will be merged after https://github.com/amplitude/Amplitude-TypeScript/pull/442 this merge.
=> Multi instance

includes/sdk-ts-browser/shared-configurations.md
=> fix: add missing config

docs/data/sdks/browser-2/index.md, docs/data/sdks/typescript-browser/migration.md, includes/sdk-ts-browser/shared-configurations.md, includes/sdk-ts/shared-callback.md
- https://amplitude.atlassian.net/browse/AMP-78775
- https://amplitude.atlassian.net/browse/AMP-78777
=> fix: doc fix

docs/data/destinations/branch.md
As per customer question:
https://discourse.amplitude.com/t/branch-event-streaming-for-anonymous-users/11055/6
=> AMP-78776 [streaming] remove incorrect info about anonymous users in Branch.io

docs/data/sdks/typescript-react-native/migration.md, includes/sdk-ts-browser/shared-configurations.md, mkdocs.yml
https://pr-819.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-react-native/migration/
=> AMP-78205 - Update React Native migration doc

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md, docs/data/sources/google-tag-manager-client-legacy.md, includes/sdk-troubleshooting-and-debugging/common-issues.md, includes/sdk-troubleshooting-and-debugging/latest-android.md, includes/sdk-troubleshooting-and-debugging/latest-ios.md, includes/sdk-troubleshooting-and-debugging/latest-plugin.md, includes/sdk-troubleshooting-and-debugging/latest-sdk-event-callback.md, includes/sdk-troubleshooting-and-debugging/latest-sdk-how-to-debug.md, includes/sdk-troubleshooting-and-debugging/legacy-android.md, includes/sdk-troubleshooting-and-debugging/legacy-how-to-debug.md, includes/sdk-troubleshooting-and-debugging/legacy-ios.md
latest android: https://pr-834.d19s7xzcva2mw3.amplifyapp.com/data/sdks/android-kotlin/#troubleshooting-and-debugging
legacy android: https://pr-834.d19s7xzcva2mw3.amplifyapp.com/data/sdks/android/#troubleshooting-and-debugging
latest ios: https://pr-834.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift/#troubleshooting-and-debugging
legacy ios: https://pr-834.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios/#troubleshooting-and-debugging
=> Mobile debug doc

docs/data/destinations/hubspot-event-streaming.md, docs/data/destinations/intercom.md, docs/data/destinations/mailchimp-event-streaming.md, mkdocs.yml
Add docs for Mailchimp streaming. Clean up linter errors in HubSpot docs.
End of week
=> AMP-76919 Add Mailchimp streaming docs

docs/data/sdks/android-kotlin/migration.md, mkdocs.yml
https://pr-843.d19s7xzcva2mw3.amplifyapp.com/data/sdks/android-kotlin/migration/
=> AMP-78613 - Update Android migration guide

docs/data/sources/airbridge.md
Hi, this is [Airbridge](https://airbridge.io) team.
- Airbridge Help center has been updated recently
- we support redirects for the old address, but would be better to use the new address
ASAP, But the priority is low.
=> docs: Update Airbridge document link

docs/data/sdks/ios/index.md, docs/data/sdks/typescript-react-native/index.md, docs/data/sdks/typescript-react-native/migration.md, includes/sdk-android/android-sdk-advertiser-id.md
* New docs for IDFA, IDFV, ADID, and AppSetID support in React Native
* Update RN migration docs
* Fix typos, lint
https://pr-853.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-react-native/#advertising-identifiers
=> feat: add React Native (TS) IDFA, IDFV, ADID, and AppSetId instructions

docs/data/sdks/android-kotlin/index.md
Add more doc related to how to set the configuration after init in kotlin sdk. Related to this [GitHub question](https://github.com/amplitude/Amplitude-Kotlin/issues/136).
=> feat: add dynamic configuration example in kotlin

docs/data/sources/bigquery.md
Add contact emails for BigQuery GA4 beta customers
- [Y] Doc update.
- [Y] My documentation follows the style guidelines of this project.
- [Y] I previewed my documentation on a local server using `mkdocs serve`.
- [Y] Running `mkdocs serve` didn't generate any failures.
- [Y] I have performed a self-review of my own documentation.
=> AMP-80277 Add contact emails for BigQuery GA4 beta customers

docs/data/sdks/typescript-browser/index.md
Fixes type in Browser SDK docs
Asap
=> Fixes type in Browser SDK docs

docs/analytics/apis/http-v2-api-quickstart.md
=> Fixes incorrect Amplitude ingestion URL

CONTRIBUTING.md, cspellignore.txt
=> Adds documentation on how to allow an unknown word

docs/data/sdk-plugins.md
https://pr-887.d19s7xzcva2mw3.amplifyapp.com/data/sdk-plugins/#enrichment-type-plugin_1
=> feat: add more enrichment plugin example

docs/data/destinations/google-pub-sub-cohort.md, docs/data/destinations/kinesis-data-stream-cohort.md
These are new cohort sync destinations.
Refer: https://docs.google.com/document/d/1NahJSj_sUQ_3uVHOcXE9xJ1j0vlQoAAg-HkHFnEO1Wo/edit
08/07/23
=> AMP-81722 [Cohort Docs] Added cohort streaming docs for pubsub and kinesis

docs/experiment/sdks/nodejs-sdk.md
Update to Experiment Node Server SDK docs for automatic assignment tracking
=> Auto-assignment-tracking

docs/data/sdks/ios-swift/migration.md, docs/data/sdks/sdk-quickstart.md
Update `import Amplitude_Swift` to normalized `import AmplitudeSwift`
=> AMP-81996 Update `import Amplitude_Swift` to `import AmplitudeSwift`

docs/data/sdks/browser-2/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, includes/sdk-browser-supported-version.md
for ticket: https://amplitude.atlassian.net/browse/AMP-81914
=> AMP-81914 Add supported browser version

overrides/main.html
Adds a verification meta tag for the Google Search Console. This will provide insight into our Google search 
performance, and visibility into how we are indexed by Google.
ASAP
=> add the search console verification tag

docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-react-native/index.md
* update RN support versions to latest after testing (0.68, 0.69, 0.70, 0.71, 0.72)
* remove RN CLI versions for conciseness (this is dependeny on RN version)
=> chore: update RN support versions to latest, remove RN CLI versions

docs/data/sources/google-tag-manager-client.md
https://pr-888.d19s7xzcva2mw3.amplifyapp.com/data/sources/google-tag-manager-client/?h=gtm
- added the warning for breaking changes
- added the breaking changes checklist
- added the new features related to DES and re-ordered the sections to make them align with the template UI.
=> feat: init GTM Browser 2.0

CODEOWNERS
Adding Mark to CODEOWNERS file
N/A
=> Add Mark to CODEOWNERS

docs/data/sources/google-tag-manager-client.md
- tweaks for revised template
- move breaking changes to bottom, clarify instance name usage, reorg DET options
=> template useability docs changes

docs/experiment/sdks/go-sdk.md, docs/experiment/sdks/python-sdk.md
Update dev docs for Experiment Go SDK auto assignment tracking feature
=> Update dev docs for Experiment Go SDK auto assignment tracking feature

docs/assets/images/experiment/client-side-overview.drawio.svg, docs/assets/images/experiment/server-side-local-overview.drawio.svg, docs/assets/images/experiment/server-side-remote-overview.drawio.svg, docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/index.md, docs/experiment/sdks/javascript-sdk.md
Update documentation for client-side local evaluation:
1. Update javascript SDK with new functions and local evaluation info.
2. Update experiment index.md with client-side local evaluation in system overview.
3. Update  local evaluation page with for client-side sdks and implementations.
Today/Tomorrow
=> initial client-side local evaluation docs updates for js sdk

docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios-swift/migration.md
Update Swift SDK docs for Swift GA
* Use diff views in migration doc for easier comparison
* https://pr-928.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift/migration
* Add `migrateLegacyData` info
* https://pr-928.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios#configuration 
=> chore: update Swift SDK docs for GA

docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-react-native/ampli.md, includes/ampli/ampli-ts-client.md, includes/sdk-ts-browser/ampli.md
Related to https://amplitude.atlassian.net/browse/AMP-82578.
Mention that they can use ampli.client to access other functions in sdk.
=> feat: mention the ampli.client in ampli.md

docs/data/sources/bigquery.md
Added section for updating Service Account Key for BigQuery Import
ASAP :)
=> Update BigQuery Source info re Service Account Key

docs/data/destinations/thetradedesk-cohort.md
- updated the part of user mapping 
- updated the part of consideration (with explanation of Time-to-Live parameter)
=> AMP-84981 updated TradeDesk cohort sync docs

docs/data/sdks/javascript/index.md, includes/sdk-browser-supported-version.md
https://amplitude.atlassian.net/browse/AMP-81914
=> fix: add link to TS SDK
