docs/analytics/apis/user-profile-api.md
Profile API no longer returns an error for new users, so I removed that section. However, we do return throttling errors if a client sends too many requests, so I added that section in.
=> Update Considerations section of Profile API

docs/data/debugger.md
Fixed incorrect image paths that were causing console warnings .
Whenevs
=> fixing image paths that were throwing log warnings

CONTRIBUTING.md, README.md
Fixes some spelling in `CONTRIBUTING.md`
N/A
@caseyamp
=> Fix minor spelling mistake in CONTRIBUTING.md

docs/data/ampli/git-workflow.md
[AMP-55661](https://amplitude.atlassian.net/browse/AMP-55661) removed beta notice on Git workflow 
- [x ] Doc update.
- [ x] My documentation follows the style guidelines of this project.
- [ x] I previewed my documentation on a local server using `mkdocs serve`.
- [ x] Running `mkdocs serve` didn't generate any failures.
- [ x] I have performed a self-review of my own documentation.
@caseyamp
=> removed beta notice on Git workflow

docs/experiment/apis/evaluation-api.md, docs/experiment/general/exposure-tracking.md, docs/experiment/guides/getting-started/fetch-variants.md, docs/experiment/guides/getting-started/track-exposure.md, docs/experiment/index.md, docs/javascripts/api-table.js, docs/stylesheets/extra.css, includes/experiment-interactive-evaluation-api-table.md, includes/experiment-interactive-exposure-table.md, includes/experiment-interactive-exposure-tracking-table.md, includes/experiment-interactive-fetch-table.md, mkdocs.yml, overrides/partials/integrations/analytics/amplitude.html
This is a project I worked on this week in preparation for the dev docs GA. I know that a commonly used feature of the readme.com site was the interactive api, where the user could send requests from the browser.
This PR adds initial implementations for sending requests from the browser. Eventually I want to abstract this out and make a mkdocs plugin for generating these tables based on some schema, but that is currently out-of-scope and would require a lot more work.
@caseyamp
=> Interactive API tables for experiment APIs and getting started guide

docs/analytics/apis/releases-api.md
See:
.NET https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
Java https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html?is-external=true
JS https://date-fns.org/v2.28.0/docs/format
Because this is equivalent to a typo, I don't think the following apply.
@caseyamp
=> releases-api: use a copy/pastable date format

docs/data/sources/amazon-s3.md
Fix aws account and external id in S3 import doc
Please read thread for details https://amplitude.slack.com/archives/CMW3ZELRE/p1656597999363599?thread_ts=1656529407.024349&cid=CMW3ZELRE. In summary, fix the s3 import instruction to reduce confusions when setting up IAM roles for s3 import.
ASAP.
@caseyamp
=> AMP-56307 Fix aws account and external id in S3 import doc

docs/analytics/apis/dashboard-rest-api.md
As Amplitude user I found typos in the documentation that I have been working with. The existing chart request won't work without the '/query' part after the 'chart_id', which is missing in the example. And the users request example has 'users?users?' part which causes the error, and should instead be 'users?' just one time.
Doc update.
=> Typos fixes in Dashboard API doc

docs/data/sdks/android-ampli.md, docs/data/sdks/android-kotlin-ampli.md
https://amplitude.atlassian.net/browse/AMP-56590
- [x ] My documentation follows the style guidelines of this project.
- [x ] I previewed my documentation on a local server using `mkdocs serve`.
- [x ] Running `mkdocs serve` didn't generate any failures.
- [x ] I have performed a self-review of my own documentation.
@caseyamp
=> removed unnecessary minSdkVersion in Ampli android docs

docs/data/sdks/typescript-browser.md
Addded missing Ampli wrapper info to top of TypeScript SDK page
https://amplitude.atlassian.net/browse/AMP-56802
@caseyamp
=> added Ampli header to TypeScript SDK docs

docs/experiment/general/evaluation/local-evaluation.md
Add a row to the benchmarking table for golang sdk
asap
@caseyamp
=> add local evaluation benchmarks for golang sdk

docs/data/ampli/cli.md
https://amplitude.atlassian.net/browse/AMP-49885
* updated ampli status docs to include all current options
* Includes sourceDir, instanceName, is-merged and is-latest
@caseyamp
=> updated ampli status docs to include all current options

docs/data/ampli/cli.md, mkdocs.yml
* Added missing options to `ampli pull` - `omit-api-keys`, `include-api-keys`
* Renamed legacy "JavaScript" to "Browser"
@caseyamp
=> Amp 57412 ampli docs add all new options to ampli pull docs

docs/data/ampli/middleware.md
https://amplitude.atlassian.net/browse/AMP-57508
added note about middleware usage in Browser SDKs
@caseyamp
=> added note about middleware usage in Browser SDKs

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/react-native-sdk.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md
Adds EU data residency section for browser, node, react native and kotlin
Earliest convenience
@caseyamp
=> adds eu data residency code snippets

docs/data/sdks/android-kotlin/index.md
Add the enrichment type and destination type example of Android-Kotlin plugins.
Reference: https://github.com/amplitude/ampli-examples/pull/129/files
@caseyamp
=> add android kotlin plugin example

docs/data/sdks/typescript-browser/migration.md, mkdocs.yml
Adds migration guide for moving from `amplitude-js` to `@amplitude/analytics-browser`
N/A
@caseyamp
=> Adds migration docs for @amplitude/analytics-browser

docs/data/ampli/index.md
Fix amplitude sdk heading typo and fix a code example. 
Whenever
=> Fix heading and code example

docs/data/sdks/react-native-sdk.md, docs/data/sdks/typescript-browser/index.md
* Removes inaccurate note on tracking options
* Removes unused tracking options
* Adds code sample for tracking options usage
Code update: https://github.com/amplitude/Amplitude-TypeScript/pull/193
Earliest convenience
@caseyamp
=> Removes unused tracking options and adds code sample for usage

docs/data/sdks/android/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/node/index.md, docs/data/sdks/react-native/index.md, mkdocs.yml
Standardize the three legacy SDK docs header:
React Native
Javascript
Android 
Headers:
1. Package registry version
2. SDK description
3. SDK Resources
4. Legacy info and new SDK "up sell"
5. Ampli wrapper "up sell"
@caseyamp
=> legacy sdk header updates

docs/data/sdks/flutter/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, docs/data/sdks/unity/index.md
Standardize the 2 Bata SDK docs header:
TS Node 
TS RN
Headers:
Package registry version
SDK description
SDK Resources with beta block
no ampli warning
link fix for dynamic config in flutter and unity page
@caseyamp
=> Beta core SDK header update

includes/data-sources-sdks.md
I accidentally changed the wrong paths for other SDKs in [last PR](https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/189/files#diff-f6f96aa4d090f5208b9aad089cbe1f55ade10b9b6a88c2ceb1ce9b4f6aa637eb)
Correct them here 
@caseyamp
=> AMP-56383 - Update data-sources-sdks.md

docs/analytics/apis/attribution-api.md, docs/analytics/apis/group-identify-api.md, docs/analytics/apis/identify-api.md, includes/auth-api-key-query-param.md
Create new reusable and update some of the API docs to reflect that the API key is passsed in the query, not the body. 
ASAP
=> DDI-199 create new reusable for API Key auth in query params

docs/data/sdks/android-kotlin/index.md
Add clarification for read_phone_state purpose. 
Casual
=> DDI-206 Clarify READ_PHONE_STATE info

docs/data/sdks/android-kotlin/index.md
https://amplitude.atlassian.net/browse/AMP-59705
* Updated the dependency section to include `1.0+` rather than `1.0.0` as `1.0.0` has bugs and is causing customer issues. 
* Added link to android koltine releases in Maven Central
* Updated min SDK to 16 to match the version in gradle
@caseyamp
=> AMP-59705 update kotlin docs latest dependency version and minSdk

docs/data/sdks/javascript/index.md
Add startNewSession param to legacy js doc. 
Casual
=> DDI-84 Add startNewSession param to doc

docs/data/destinations/amazon-s3.md
Adds data export format section and merged ID section to S3 export docs. 
ASAP
=> DDI-214 Add data export section to S3 export docs. 

.github/workflows/cron-link-check.yml, .github/workflows/mega-linter.yml
We recently changed the Megalinter action to only lint the diff so we use fewer minutes and checks complete faster. Because we no longer check the entire doc set on every pull, we risk links becoming broken without any warning. This PR adds a cron job github action to check for broken links every day at 12:00 AM. 
Casual
=> DDI-220 Cron Job for Link Checking

docs/analytics/apis/group-identify-api.md
https://discourse.amplitude.com/t/group-identify-api-is-it-possible-to-batch-requests/3933/6?u=jshek
Added throttling limits for group identify API
Not urgent but important 
@caseyamp
=> Added throttling limits

docs/data/sdks/javascript/index.md
Fixed typos for `includeFclid`, changed it to `includeFbclid`.
@caseyamp
=> fixed typo error

docs/data/sdks/javascript/index.md, docs/data/sdks/typescript-browser/index.md
- docs: add cross domain section for typescript browser sdk
@caseyamp
=> docs: add cross domain section for typescript browser sdk

docs/analytics/apis/group-identify-api.md
The mapping of the fields were incorrect - updated to include some examples.
Changed Group Identify docs to reflect accurate mappings - discourse here: https://discourse.amplitude.com/t/set-add-with-the-batch-api-for-groupidentify-requests/8775/10
Fixed mappings
Not super urgent but required to avoid incorrect instrumentation
@caseyamp
=> Revised field mapping - previously invalid format

docs/analytics/apis/taxonomy-api.md
Seems we get to pay for the privilege to make sure the docs are up to date 😂 
The documentation for the response type is incorrect. When making a request to the endpoint per:
```
GET /api/2/taxonomy/event HTTP/1.1
Host: amplitude.com
Authorization: Basic {{api-key}:{{secret-key}}}
```
Source: https://www.docs.developers.amplitude.com/analytics/apis/taxonomy-api/#get-all-event-types
Instead of being the response type in the docs the response is instead:
```
~/w/canva jack-taxonomy-worker-deploy *2 !386579
> curl https://amplitude.com/api/2/taxonomy/event -u api-key:secret-key -X GET 
{"success": true, "data": [{"event_type": "event1", "category": null, "description": "account"}, {"event_type": "event2", "category": null, "description": "account"}]}
```
ASAP
@caseyamp
=> Correct the response type for getting all events

docs/analytics/apis/taxonomy-api.md
```
> curl https://amplitude.com/api/2/taxonomy/event -u api-key:secret-key -X GET                                   
{"success": true, "data": [{"event_type": "event1", "category": {"name": "account"}, "description": "null"}]}
```
```
> curl https://amplitude.com/api/2/taxonomy/event/test%20event3 -u api-key:secret-key -X GET
{"success": true, "data": {"event_type": "test event3", "category": {"name": "account"}, "description": null}}
```
My previous PR was wrong because my category was `null` which obfuscated the nested category name.
@caseyamp
=> Fix response type

docs/data/sources/amazon-s3.md
improve s3 docs by clarifying how prefixs should be setup when importing from root
@caseyamp
=> AMP-62458 improve s3 docs by clarifying how prefixs should be setup when importing from root

docs/data/converter-configuration-reference.md
Adds section for `$skip_user_properties_sync` to the converter ref. 
ASAP
=> Adds Skip User Properties Sync section

docs/data/iglu-api.md
Fixed trailing slash in schemas API example
ASAP
https://discourse.amplitude.com/t/data-iteratively-api-to-extract-taxonomy-returns-400-error/8883/2
@caseyamp
=> Fixed trailing slash in schemas API example

docs/data/sdks/android/ampli.md, docs/data/sdks/android/index.md
Update legacy android SDK badge based on the Shileds [doc](https://shields.io/category/version)
@caseyamp
[DXOC-298]: https://amplitude.atlassian.net/browse/DXOC-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: fix legacy android sdk badge

docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/sdk-ts-browser/shared-configurations.md
This PR includes:
- Add ts logging doc
- Fix minor import typos in ts node and ts react-native docs
@caseyamp
=> docs: add ts logging doc, fix minor import typos

docs/data/converter-configuration-reference.md
Adding a section for user property operations for converter config
ASAP
=> DDI-267 Adding section for user prop operators

docs/data/sdks/index.md, mkdocs.yml, overrides/home.html, overrides/main.html
After a conversation with an internal customer, I realized that the Quickstart guide wasn't easily findable. So I promoted it a bit and gave it a page icon. Also made small changes to site home page. 
ASAP
=> DDI-277 Make SDK Quickstart guide easier to find

docs/data/sdks/android/index.md, docs/data/sdks/flutter/index.md, docs/data/sdks/ios/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/react-native/index.md, docs/data/sdks/unity/index.md, docs/data/sdks/unreal/index.md
The old SDK is is using http v1 internally, it's not support overwrite min_id_length
@caseyamp
=> remove the httpv2 notice for sdk using httpv1

docs/data/sdks/typescript-browser/index.md
Adds specific callouts for differences between the default SDK and our marketing plugins. Added to plugins section rather than marketing analytics sdk docs because MA SDK is targeted at newer and less sophisticated customers.
@caseyamp
=> Add plugin differences section

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, docs/data/sdks/ios/index.md
Adds sections for how we derive carrier info to Android and iOS.  
🤷 
-
=> DDI-290 Adds info about mobile carrier

docs/data/ampli/index.md
Adds list of unsupported SDKs to Ampli Wrapper. 
Whenever
=> DDI-293 Add note about unsupported SDKs

docs/analytics/apis/taxonomy-api-2.md
Added Taxonomy 2.0 API page that mostly explains how to do operations described on Taxonomy API page using new GraphQL API (more a migration guide rather than documentation). Since it's a concept, it's excluded from search and nav.
@caseyamp
=> AMP-63782 GraphQL Taxonomy API 2.0 concept

docs/analytics/apis/taxonomy-api-2.md
AMP-63782 GraphQL Taxonomy API 2.0 fixed draft state callout
@caseyamp
=> AMP-63782 GraphQL Taxonomy API 2.0 fixed draft state callout

docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md
- add subset flag support description in Experiment Android, JS, iOS
- Going to hold util the changes released
@caseyamp
=> doc: add subset flag doc for experiment android, ios, js

includes/sdk-ts-browser/shared-configurations.md
Fixes useBatch copy paste error in a shared config table. 
🤷
=> DDI-299 Fixes copy paste error in table

docs/analytics/apis/identify-api.md, includes/auth-api-key-query-or-body-param.md
Shaping up the Identify API docs to make them easier for users to get started. 
- Clarified accepted body formats. It initially wasn't clear that body params had to be `form-data` or `x-www-form-urlencoded` and that raw JSON isn't accepted. 
- Clarified auth instructions
- Clarified when to use query vs body params
- Documented missing error status. 
- Also made the Postman collection link more findable by linking to the collection in the "Example request" section --  since it's not feasible to host so many code examples in the docs. 
ASAP, causing customer confusion.
=> DDI-300 updating identify API based on customer feedback

includes/auth-basic-org-key.md, includes/auth-basic.md
Adds Base64 Encoding info to basic auth reusables. 
ASAP
=> DDI-301 Adds info about base64 encoding to API basic auth reusables

includes/postman.md
London Hackathon feedback included that people didn't like the Run in Postman button and requested something "more open". 
- Added a link to the Amplitude Developer Docs profile so users without Postman accounts can browse the collection. 
- Turned the button into an inline link for people who already use postman. 
WHENEVER SHRUG
=> DDI-302 Adds different ways to browse postman collection

docs/experiment/general/performance-and-caching.md
Update experiment performance metrics with per region latency from synthetic tests over the last 6 mo.
N/A
@caseyamp
=> update performance metrics, add per region performance

docs/analytics/apis/batch-event-upload-api.md, docs/analytics/data-backfill-guide.md
Fix backfill limits confusing contradictions. 
ASAP
=> DDI-309: Backfill Limits tweaks

docs/data/destinations/redshift.md
The data types for dict properties are `SUPER` in Redshift, not String
@caseyamp
=> Correct Redshift Warehouse Export data types

docs/analytics/apis/group-identify-api.md
Fixes typo in code sample, and adds a cURL example that was missing. 
ASAP
=> DDI-325 Fixes typo and adds cURL example

docs/data/sources/intercom.md
> You can see the user property mapping preference you selected from the data source detail page for Intercom.
Looking to improve the wording here. The page I'm referring to is this: https://analytics.amplitude.com/amplitude/connections/project/187520/sources/detail/bGlicmFyeTphZGFwdGVyL2ludGVyY29t
Here is a lucid diagram of the new flow: https://lucid.app/lucidchart/a20cb365-6aab-450b-9f26-eec165c6507e/edit?viewport_loc=-139%2C-53%2C2269%2C1245%2CTqnafomwO3dB&invitationId=inv_836b9c96-c5ba-4973-b29e-7c39c87996d0
- Updated wording to reflect properties of new Intercom source integration
- users no longer require a valid intercom ID that maps to Amplitude users. Instead, a choice can be made to map from Intercom users' user ID or email to Amplitude User IDs.
- Updated set up guide to …
=> Update Intercom Dev Doc for Intercom Source v2

docs/javascripts/statuspage.js, mkdocs.yml, overrides/home.html, overrides/partials/footer.html
Embeds the Amplitude Status Page widget and adds link to the status page to the footer. 
Whenever
=> DDI-323 Add statuspage integration and link to status page to footer

docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/go-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/jvm-sdk.md, docs/experiment/sdks/nodejs-sdk.md, docs/experiment/sdks/python-sdk.md, docs/experiment/sdks/react-native-sdk-legacy.md, docs/experiment/sdks/react-native-sdk.md, docs/experiment/sdks/ruby-sdk.md
I added information on configuring Experiment SDKs to connect to the EU DC for all Experiment SDKs, by adding a blue info bubble calling out the setting after every "Configuration" section. For SDKs with remote and local eval, this info shows up once for each.
ASAP, but no real deadline.
@caseyamp
=> Added info on configuring Experiment for EU DC

docs/experiment/general/evaluation/local-evaluation.md, includes/data-sources-sdks.md, mkdocs.yml
* Experiment 
* Move ruby up in left nav since GA
* Remove beta tag and versions from local evaluation table
* Analytics SDKs
* Update grid to remove legacy nodejs sdk and change golang from alpha to beta.
@caseyamp
=> update sdk release milestones and versions

docs/experiment/apis/management-api.md
Add the following endpoints to Experiment Management API:
- /flags/list
- /flags/{:id}
- /experiments/{:id}/versions
- /experiments/{:id}/versions/{:versionId}
- /flags/{:id}/versions
- /flags/{:id}/versions/{:versionId}
The feature is live on prod, and customers will be notified of this change asap.
@caseyamp
=> add documentation on flag list, flag details, and experiment/flag versions APIs to management api

includes/sdk-ts-browser/shared-configurations.md
Fix absolute link in a reusable to go to the right place.
=> DDI-338 Fix absolute link that goes to the wrong place

mkdocs.yml
Adds script to footer to pull in current year.  
Soon
=> DDI-339: Update footer copyright to auto-update for year

docs/data/sources/snowflake.md
Milliseconds need to be divided by 1000.0 before converting to timestamp for an accurate timestamp.
Divide epoch timestamp in milliseconds by 1000.0 before converting to ntz timestamp. Resulting timestamp would be innacurate otherwise. 
just a friendly fix proposed
@caseyamp
=> Correct timestamp common snippet snowflake.md

mkdocs.yml
- fix: add beta tag and remove ampli for ios swift beta sdk
@caseyamp
=> fix: add beta tag and remove ampli for ios swift beta sdk

docs/data/sdks/index.md, docs/data/sources.md, docs/data/sources/client-side-vs-server-side.md, includes/data-sources-sdks-client-side.md, includes/data-sources-sdks-server-side.md, mkdocs.yml
Adds client vs server side explainer doc and reorganizes SDK catalogs for client side versus server side. 
Whenever
=> DDI-317 Adding Client-side vs Server-side doc

docs/analytics/apis/identify-api.md
Adds missing optional identifiers to optional params in Identify API doc. 
ASAP
=> DDI-360 Adds missing Optional identifiers to some params

docs/data/ampli/integrating-with-ci.md
Update CI docs to remove deprecated `ampli-swift` docker image.
@caseyamp
`markdownlint` detects a dead link `https:/https://docs.developers.amplitude.com/data.amplitude.com/`
It looks like some patterns (https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/blob/main/.markdown-link-check.json#L73) incorrectly convert original link `https://data.amplitude.com/` to the incorrect  `https:/https://docs.developers.amplitude.com/data.amplitude.com/`
=> AMP-66512 Update CI docs to remove deprecated ampli-swift docker image

docs/analytics/apis/user-privacy-api.md
Update User Privacy API doc to reference managing user privacy notifications instruction
Link to managing user privacy notifications instruction so that users using User Privacy API knows how to manage user privacy notifications.
N/A
- [*] Doc update.
- [*] My documentation follows the style guidelines of this project.
- [*] I previewed my documentation on a local server using `mkdocs serve`.
- [*] Running `mkdocs serve` didn't generate any failures.
- [*] I have performed a self-review of my own documentation.
@caseyamp
=> AMP-63980 Update User Privacy API doc to reference managing user privacy notifications instruction

docs/analytics/apis/user-profile-api.md, mkdocs.yml
Adds new-format examples to User Profile API doc.  
Whenever
@caseyamp
=> DDI-359 Adds examples to user profile API doc

docs/data/ampli/plugin.md, docs/data/sdks/android-kotlin/index.md, docs/data/sdks/go/index.md, docs/data/sdks/python/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md
Updates docs for plugin to specify correct return type. Previously it stated null or undefined which is incorrect. Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/308
@caseyamp
=> Updates docs for plugin to specify correct return type

docs/data/sdks/android-kotlin/ampli.md, docs/data/sdks/android/ampli.md, docs/data/sdks/go/ampli.md, docs/data/sdks/ios/ampli.md, docs/data/sdks/java/ampli.md, docs/data/sdks/javascript/ampli.md, docs/data/sdks/node/ampli.md, docs/data/sdks/python/ampli.md, docs/data/sdks/react-native/ampli.md, docs/data/sdks/typescript-browser/ampli.md, docs/data/sdks/typescript-node/ampli.md, docs/data/sdks/typescript-react-native/ampli.md, includes/ampli/flush/ampli-flush-section.md, includes/ampli/flush/ampli-flush-snippet-go.md, includes/ampli/flush/ampli-flush-snippet-ios.md, includes/ampli/flush/ampli-flush-snippet-java.md, includes/ampli/flush/ampli-flush-snippet-python.md, includes/ampli/flush/ampli-flush-snippet-typescript.md
https://amplitude.atlassian.net/browse/AMP-67032
Add flush section to Ampli docs
@caseyamp
=> AMP-67032 added flush documentation to Ampli node docs

.github/styles/Amplitude/Headings.yml, docs/guides/amplitude-keys-guide.md, docs/stylesheets/extra.css, includes/auth-basic-org-key.md, mkdocs.yml
Adds a guide to the various keys and tokens a user may encounter when using Amplitude. 
ASAP
=> DDI-364 Create a guide to Amplitude Keys and Tokens

docs/data/ampli/plugin.md
Users not only need to be on the latest Ampli, but also on the latest Amplitude browser SDK. If you upgrade Ampli without switching to the new Amplitude SDK, plugins are not supported. Linked to the migration doc which explains the difference and how to migrate.
N/A
@caseyamp
=> Clarify plugins note on Ampli version

docs/data/sources/snowflake.md
Update dev docs that Snowflake time-based import requires timestamp without timezone (TIMESTAMP_NTZ format). Also update the code snippet for the common conversion from TIMESTAMP_TZ -> TIMESTAMP_NTZ.
N/A, ASAP
@caseyamp
=> Amp 67569 Update doc for Snowflake time-based import that requires TIMESTAMP_NTZ format

mkdocs.yml
Make links to dev doc pages on home page relative so they open in same tab. 
Not sure this is supported with our template setup, but I need to find some solution for this. 
ASAP: suboptimal user experience.
=> DDI-399: Fix home page links to open in same tab

docs/data/sdks/go/index.md
fix the go get url
Before
After
@caseyamp
=> fix the go get url

docs/data/ttl-configuration.md, mkdocs.yml
There are a handful of orgs who have TTL self-serve, so I think it makes sense to add the self-serve instructions
Updating TTL docs to include self-serve instructions
Whenever possible, but not pressing.
@caseyamp
=> Adding TTL Config. self-serve instructions

docs/all-resources.md, docs/analytics/apis/index.md, docs/analytics/index.md, docs/data/index.md, docs/data/sdks/index.md, docs/documentation-home.md, docs/experiment/index.md, docs/guides/index.md, docs/index.md, docs/partners/index.md, overrides/partials/content.html
Adds a link to the community in article footers.
=> DDI-402: Adding community help link in footers

docs/data/sdks/python/index.md
- Add python supported version information for Python SDK. 
- Add new shutdown behavior
@caseyamp
[AMP-66979]: https://amplitude.atlassian.net/browse/AMP-66979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-66979 add python supported version and shutdown behavior update

docs/analytics/domain-proxy.md
Adds table for all server URLs for domain proxy by SDK.
=> list  server url for proxy for different sdks

docs/guides/amplitude-keys-guide.md
Fixed weird tooltips on table icons. That started after recent version upgrade. 
ASAP
=> DDI-382 Fix table icon tooltips

docs/data/sdks/typescript-react-native/index.md, insiders.mkdocs.yml, mkdocs.yml
Limited TOC depth to L3 headings to make tocs easier to navigate and less hideous on longer articles. Also fixes tooltip text for anchor links. 
ASAP
=> Add fix for TOC depth and better anchorlink tooltip text

docs/data/sdks/sdk-quickstart.md
I noticed there were broken links on the quick start guide. 
This is due to the fact the relative reference was resolving to the incorrect path 
e.g. `data/sdks/sdks/unity`
I fixed this and tested it locally.
Before:
https://www.loom.com/share/2cf0d87fffda4af6a031d7b9622ae881
After:
https://www.loom.com/share/1e6801e90f1443f69e69275320cc6c54
@caseyamp
=> AMP-67753 fix broken quickstart links

docs/experiment/apis/management-api.md, docs/experiment/index.md
- rearrange existing sections so it is easier to read documentation
- add new parameters to `/experiments/new` and `flags/new` endpoints
- add the followings endpoints for both flags/:id and experiments/:id
-- PATCH 
-- POST /variants/:variantKey/users
-- POST /variants
-- PATCH /variants/:variantKey
-- DELETE variants/:variantKey
-- DELETE variants/:variantKey/users/:userIndex
Once we deploy the appropriate backend changes (scheduled for week of 1/23/23).
@caseyamp
=> Update experiment mgmt api variants

docs/data/sdks/react-native/index.md, docs/data/sdks/sdk-quickstart.md, docs/data/sdks/typescript-react-native/ampli.md, docs/data/sdks/typescript-react-native/index.md, mkdocs.yml
Removes beta label from new react native sdk
@caseyamp
=> Removes beta label from new react native sdk

docs/experiment/guides/getting-started/create-a-deployment.md, docs/experiment/guides/getting-started/fetch-variants.md, docs/experiment/guides/getting-started/index.md, docs/experiment/index.md, mkdocs.yml
Adds an index page to introduce reader to the guide and to make breadcrumb nav useful. 
🤷
=> DDI:367: Add index for Experiment getting started

docs/data/sdks/android/index.md
- Add configuration section for legacy Android SDK
- We could discuss further how we prefer this section to be aligned.
[AMP-68179]: https://amplitude.atlassian.net/browse/AMP-68179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-68179 add legacy android configuration section

docs/data/sdks/android/index.md
- add identify volume reduction in developer doc
[AMP-68175]: https://amplitude.atlassian.net/browse/AMP-68175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-68175: add identify volume reduction in Android doc

.github/styles/Vocab/dev/accept.txt, docs/data/sources/amazon-s3.md
Adds dedupe section for using `insert_id`
ASAP
=> DDI-422 Add Dedupe Section to Amazon S3 import

docs/data/sources/client-side-vs-server-side.md
Currently, APIs are categories under server side which is not true. It is necessary to let customer know that both Analytics and Experiment SDKs use API endpoints, so that they can implement custom solutions for languages not supported.
- Added a relationship table for SDKs and APIs
- Updated broken links. 
=> DDI 411 [Contextual Doc] Client side vs server side 

docs/data/ampli/plugin.md, docs/data/deprecated-sdks/android.md, docs/data/deprecated-sdks/browser.md, docs/data/sdks/android/index.md, docs/data/sdks/ios-swift/migration.md, docs/data/sdks/javascript/index.md, docs/data/sdks/node/index.md, docs/data/sdks/react-native/index.md, docs/data/sdks/sdk-overview.md, docs/data/sdks/typescript-browser/migration.md, mkdocs.yml
Currently we use “legacy” in our dev doc for old version SDKs. It sounds too negative and customers usually don’t want to use it. But actually we still support bug fixes for these old SDKs. So after [discussion](https://amplitude.slack.com/archives/C04J4LN147Q/p1676323676183759), we agree to use “maintenance” over “legacy”.
=> DDI 424 [Contextual Doc] Use "maintenance" over "legacy"

docs/experiment/guides/troubleshooting/exposures-without-assignments.md
This is what we talked about today with regards to the delayed exposure event. assignment was before the email is sent and exposure is when the email is opened. https://experiment.amplitude.com/roofr1/328890/config/30409/monitor
=> SKY-2567 add delayed exposure event information

docs/data/sources/segment.md
- add "Set up Segment Destinations" section 
- explicitly ask customers to connect the Segment Destination with one of their Segment Sources
- explicitly ask them to send data to Segment as some new customers are not aware that they need actually send data to Segment and think it is like GTM. 
- explicitly ask them to check for success in Amplitude product 
- fixed broken links
- updated method name mappings between Segment and Amplitude
Preview: https://pr-590.d19s7xzcva2mw3.amplifyapp.com/data/sources/segment/
=> DDI 412 [Contextual Doc] Segment Guide

docs/data/sources/google-tag-manager-client-legacy.md, docs/data/sources/google-tag-manager-client.md, docs/data/sources/google-tag-manager-server.md, docs/data/sources/google-tag-manager.md
- Rephrased the description of `init` tag in GTM. 
- Added EU config instructions
=> DDI 408 [Contextual Doc] GTM Guide - Add EU

docs/documentation-home.md, docs/index.md
The Amplitude Data Section misses import parts of Amplitude Data: data collection, and data governance/ CDP. 
Altered the sentence for context of what Amplitude Data is from 
>  Amplitude Data lets you integrate, resolve and manage a complete, comprehensive view of your customer and product data. 
to 
> Amplitude Data lets you capture, manage, and improve the quality of your customer and product data across Amplitude.
=> DDI 415 [Contextual Doc] Documentation Home Page 

docs/data/sdks/android-kotlin/index.md
- add doc about identify volume eduction
- add configuration section
[AMP-69871]: https://amplitude.atlassian.net/browse/AMP-69871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-69871 add identify volume reduction and configuration in android kotlin

docs/data/sdks/ios-swift/index.md
* add Swift SDK Initialize and Configuration sections
=> feat: AMP-69957 add Swift SDK Initialize and Configuration sections

docs/analytics/find-api-credentials.md, docs/data/debugger.md, docs/data/sdks/sdk-quickstart.md, includes/sdk-quickstart/quickstart-check-for-success.md
- added a link to User Look-up for debugging
- added a link to project settings for finding API key 
- fix wrong anchor links in quickstart guide by adding the number. This is caused by adding a new iOS tab. 
=> DDI 409 [Contextual Doc] In-app Navigation 

docs/data/sources/bigquery.md
adding a section to explain how time-based import works for BigQuery; similar to what we have for Snowflake–might make sense to make into a snippet eventually...
adding a section to explain how time-based import works for BigQuery; similar to what we have for Snowflake–might make sense to make into a snippet eventually...
ASAP :)
=> Adding Time-based import section explainer

docs/analytics/apis/behavioral-cohorts-api.md, docs/analytics/apis/ccpa-dsar-api.md, docs/analytics/apis/dashboard-rest-api.md, docs/analytics/apis/event-streaming-metrics-summary-api.md, docs/analytics/apis/export-api.md, docs/analytics/apis/taxonomy-api.md
* The example says user=USERID when it should be user={amplitude_id} or something (the table below is correct)
* The curl request uses --header 'Authorization: Basic {{api-key}}:{{secret-key}}' #credentials must be base64 encoded when it should just say -u {api_key}:{secret_key} 
* Update the Python example to use Basic Auth properly.
This is a quick change to fix the obvious ones. We will be following up with a Dash Rest API documentation audit next quarter.
=> AMP-70231-improve-auth-documentation

docs/data/sdks/sdk-quickstart.md, docs/data/sdks/typescript-browser/index.md, includes/sdk-ts-browser/init.md, includes/sdk-ts-browser/marketing-analytics.md, includes/sdk-ts/client-debugging.md
* Adds docs for default event tracking
* Updates code samples for browser SDK and marketing analytics SDK to include classic and module script
Affected pages/sections:
* https://pr-628.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-browser/#tracking-default-events
* https://pr-628.d19s7xzcva2mw3.amplifyapp.com/data/sdks/sdk-quickstart/
* https://pr-628.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-browser/
* https://pr-628.d19s7xzcva2mw3.amplifyapp.com/data/sdks/marketing-analytics-browser/
=> Adds docs for default event tracking

requirements.txt
Update the mkdocs-material version in requirements.txt.
I was getting an error when running locally due to: 
```
INFO     -  DeprecationWarning: invalid escape sequence '\s'
File "/usr/local/lib/python3.9/site-packages/jinja2/lexer.py", line 389, in __next__
self.current = next(self._iter)
File "/usr/local/lib/python3.9/site-packages/jinja2/lexer.py", line 650, in wrap
self._normalize_newlines(value_str[1:-1])
```
Quick google lead me to: https://github.com/squidfunk/mkdocs-material/issues/3695
I decided to use the latest version from 8.x.x.
=> Update mkdocs material verison 8.5.10

docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, includes/data-sources-sdks-client-side.md
Replaced TypeScript icon with JavaScript icon
=> Replaces JS icon

docs/data/sdks/typescript-react-native/ampli.md
- Update the React Native Ampli Wrapper doc to include react native async storage installation
Added the @react-native-async-storage/async-storage library to the React Native Ampli Wrapper installation guide, since it is required for the React Native SDK to work properly
=> update ampli.md with rn-async-storage

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/java/index.md, docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/sdk-ts-browser/shared-configurations.md, includes/sdk-ts/client-debugging.md, includes/sdk-ts/client-eu-residency.md, includes/sdk-ts/shared-batch-configuration.md, includes/sdk-ts/shared-ts-configuration.md
- Added the default configuration for 
- [next gen node SDK](https://pr-660.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-node/#configuration)
- [marketing analytics SDK](https://pr-660.d19s7xzcva2mw3.amplifyapp.com/data/sdks/marketing-analytics-browser/)
- [next gen browser SDK](https://pr-660.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-browser/#initialize-the-sdk)
- [next gen react-native SDK](https://pr-660.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-react-native/)
- Other minor fixes.
- fix the npm version badge broken issue
- alignment issue
- others
=> add more default configuration

docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-browser/migration.md, includes/sdk-ts-browser/shared-configurations.md, includes/sdk-ts/shared-ts-configuration.md
1. fixed some configuration nits.
2. add web attribution and page view tracking on the browser SDK.  There has an update on Browser SDK. Right now for web attribution and pageview tracking, it's using the plugins internally. Also, we mentioned the browser SDK web attribution parameter in the Browser SDK Migration Guide, but there is no place to explain how it works. (Check this [Github issue](https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/issues/643)). We should list the attribution configurations in the browser SDK.
=> fix configuration nits and others

docs/data/sdks/flutter/index.md
The customer has confused about trackingSessionEvent not being supported on flutter Web. They thought that means there is no session tracking logic, but that's is only for not supporting tracking session events. 
https://discourse.amplitude.com/t/needing-web-session-tracking-that-supports-the-flutter-sdk-and-wants-to-know-timeline-to-accommodate-this-request/10066
=> add more words to explain trackingSessionEvent in Flutter web. 

docs/data/sources/shopify.md
- Updated the Shopify App installation instructions to remove out of date steps and update with new method to retrieve Amplitude project API key.
- In response to this ticket: https://amplitude.atlassian.net/browse/AMP-72508; customer is trying to add Shopify as a source by following our dev doc instructions, however, it is out of date.
- Not urgent, but it's a small change and I have confirmed this method of retrieving the API key works so it should be able to go through pretty fast.
=> Update Shopify app installation instructions

docs/guides/accounts-instrumentation-guide.md
This card about using the Group Identify API is mistakenly shown in both sections when it only applies to setting user-level groups
Removed a card about setting event level groups with the Group Identify API - this is incorrect since this will persist when users are sending events without groups. Misleading to customers 
As soon as possible
=> Incorrect information on groups

docs/analytics/apis/behavioral-cohorts-api.md
Few updates:
1. Add the new API limit we have for download API
2. Update JSON with latest Cohort information -- with comments on non-obvious field on what they are 
3. Add related sections on how to retrieve extra sync metadata for all cohorts.
=> AMP-70464 update cohort API with latest info + new sync metadata parameter

docs/data/destinations/appsflyer.md, docs/data/destinations/branch.md, docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md, docs/data/destinations/meta-pixel.md, docs/data/destinations/webhooks-streaming.md
Move AppsFlyer, Branch, Braze, Customer.io, GA4, Intercom, Iterable, Meta Pixel, Webhook to GA.
Note: GA4 docs never had the beta blurb added.
=> AMP-71818 Remove beta blurbs from streaming docs

docs/data/sdks/typescript-node/index.md
* [DXOC-730](https://amplitude.atlassian.net/browse/DXOC-730?focusedCommentId=180869)
* Fix default values for flush settings to match actual values
* https://github.com/amplitude/Amplitude-TypeScript/blob/7ecfa6c826061310dfd43638080cf4f685556a8c/packages/analytics-core/src/config.ts#L25-L24
[DXOC-730]: https://amplitude.atlassian.net/browse/DXOC-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update Node TS SDK default config to have correct values for `flush` settings

docs/analytics/apis/identify-api.md
`setOnce`'s documentation was very misleading, I'm normalizing it from the setting up user properties page.
=> Update identify api documentation for setOnce

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, includes/sdk-android/android-sdk-advertiser-id.md
Based on the Android doc, https://support.google.com/googleplay/android-developer/answer/6048248?hl=en and also the customer question from [Discourse](https://discourse.amplitude.com/t/ad-id-declaration-in-the-manifest-for-android-sdk/10198/2), I added the ADID permission on both Android and Kotlin side. 
=> Android update

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/flutter/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/react-native/index.md
* Added `Mulitple Instances` and `instanceName` information to Android Kotlin docs
* https://amplitude.atlassian.net/browse/DXOC-741
=> feat: add multiple instance information to Kotlin SDK

docs/data/sdk-plugins.md
Adds destination plugin example for sending events to google tag manager client-side
Important, not urgent
=> Add plugin docs for GTM

docs/assets/csv/lookup-table-example.csv, docs/data/sources/lookup-table.md
People are asking for the sample CSV they can use for lookup tables. This PR adds an example CSV to the lookup tables docs page
=> Add lookup table CSV example

requirements.txt
Owners of the request module intentionally put out a minor version that had consequences for us due to the version of OpenSSL.
https://github.com/psf/requests/issues/6432
Trying to pin the version to see if that fixes the issue
=> Pin requests version to fix builld

docs/analytics/apis/http-v2-api.md, includes/http-api/shared-language-mapping.md
HTTP API changes language tags to language name. This was not documented in our API docs and caused https://amplitude.atlassian.net/browse/AMP-73520 ticket.  This PR documents the behavior of the API.
ASAP.
- [ X] Doc update.
- [ X] My documentation follows the style guidelines of this project.
- [ X] I previewed my documentation on a local server using `mkdocs serve`.
- [ X] Running `mkdocs serve` didn't generate any failures.
- [ X] I have performed a self-review of my own documentation.
=> AMP-73520: Added language mapping description to http-api

docs/data/sdk-middleware.md, docs/data/sdk-plugins.md
We received a lot of questions related to how to set groups at the event level in Ampli. 
Currently, the workaround is using middleware/plugins. So I added that example in the middleware and plugin docs. 
=> feat: add docs for ampli event level group support

docs/data/sdk-plugins.md
Add docs for client-side forwarding to Fullstory using our browser SDK
=> AMP-71145 Add Fullstory docs

docs/data/sdks/flutter/index.md
Fix the wrong default threshold value in the snippet comment.
https://discourse.amplitude.com/t/flutter-sdk-clarifications-on-the-default-values-for-seteventuploadthreshold-and-seteventuploadperiodmillis/10680
=> fix: fix flutter default eve upload threshold and event upload period millis

overrides/partials/content.html
- Replace emojis with svg icons
- Fix "click community link" is not tracked
- it was accidentally deleted in https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/746
- Add a `getPageInfo()` function to get commonly used info
- path: /data/sdks/typescript-browser/
- product: data
- url: https://www.docs.developers.amplitude.com/data/sdks/
=> AMP-75025 replace emojis

docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/typescript-browser/index.md, includes/sdk-ts-browser/marketing-analytics.md
1. add the new clickIds in docs. https://amplitude.atlassian.net/wiki/spaces/GOV/pages/2058289286/Browser+SDK#Cookie-Usage
2. add details for page view events
=> feat: add new doc related page view events

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android-kotlin/migration.md
Add `migrateLegacyData` configuration option to Android-Kotlin SDK.
1. Existing Java snippets (Amplitude creation) are incorrect. For example:
* https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#configuration
* https://www.docs.developers.amplitude.com/data/sdks/sdk-quickstart/#android
Some Java snippets use valid code (for example, https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#user-sessions):
```
amplitude = AmplitudeKt.Amplitude(AMPLITUDE_API_KEY, getApplicationContext(), configuration -> {
configuration.setMinTimeBetweenSessionsMillis(1000);
return Unit.INSTANCE;
});
```
In this PR I use simpler code:
```
Configuration configuration = new Configuration("AMPLITUDE_API_KEY", getApplicationContext());
configuration.setMigrateLegacyData(true); …
```
=> AMP-52578 Add `migrateLegacyData` configuration option

docs/data/sdks/ios-swift/index.md
Fix: https://amplitude.atlassian.net/browse/DXOC-853
- add more configuration fields:  https://pr-779.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift/#configuration
- add custom storage section: https://pr-779.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift/#custom-storage
=> fix: add more swift configuration

docs/guides/cookies-consent-mgmt-guide.md
https://amplitude.atlassian.net/browse/AMP-77883
Update Cookie docs to correctly show disabledCookies uses true (not “none”)
=> AMP-77883-fix-disablecookie-false

includes/sdk-ts/shared-ts-configuration.md
Type in description. Says `millionseconds` when it should be `milliseconds`.
The instructions are confusing and change is low risk. Should update now.
=> fix(docs): Update description for `flushIntervalMillis`

docs/data/sdks/typescript-node/index.md
Small typo in typescript-node docs.
Not urgent.
=> Small typo in typescript-node docs

includes/sdk-ts-browser/tracking-page-views-advanced.md
Event name is defined here:
https://github.com/amplitude/Amplitude-TypeScript/blob/7d0281ceefd6087b27f854bd3865a49eaf8f745a/packages/plugin-page-view-tracking-browser/src/page-view-tracking.ts#L32
this was incorrectly referenced as "Page Title" again.
Now.
=> fix(docs): Type when referencing the event name for Page URL

docs/data/destinations/tiktok-cohort.md
TikTok ads no longer in Beta, thus remove those sections. 
The linked JIRA has fix to bump the cohort size supported from 2.4 million to 4.8 million, also this is due to TikTok Ads API limitation, thus update related consideration so customers know what to expect. 
Added PM @Brandoncharleskhoo1 so he is aware, and wait for repo owner to approve. 
When do these changes need to be live on the site? 
N/A. Update doc so most accurate info is displayed to customers. 
=> AMP-76355 update tiktok ads doc for limitation

includes/sdk-ts-browser/tracking-page-views-advanced.md
For [this](https://amplitude.atlassian.net/browse/AMP-78261) ticket. 
link the github enrichment plugin example into the doc.
=> feat: add page view enrichment example

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android-kotlin/migration.md
This PR adds the default events tracking section for Android Kotlin SDK.
=> docs: add default events for android kotlin sdk

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android-kotlin/migration.md
Enable `migrateLegacyData` configuration option by default.
=> AMP-78784 `migrateLegacyData` configuration option is enabled by default

docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md, includes/sdk-ios/apple-deprecate-carrier.md
https://amplitude.atlassian.net/browse/AMP-78774
=> AMP-78774 - carrier cannot be tracked

docs/data/sdks/typescript-node/migration.md, mkdocs.yml
https://pr-830.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-node/migration/
Maintenance Node.js has limited APIs so this migration is not too long. Let me know if there is anything is missing here.
=> AMP-78252 - Update Node.js migration doc

docs/data/sdks/android/index.md
Put the latest-android link in legacy android. 
This is for updating the wrong link.
=> fix: fix wrong link

docs/data/sdks/typescript-browser/index.md, includes/data-sources-sdks-client-side.md, includes/sdk-ts-browser/shared-plugin-2-properties.md, includes/sdk-ts-browser/shared-plugins-2.md
Add docs for Browser SDK plugin.teardown interface
* https://pr-842.d19s7xzcva2mw3.amplifyapp.com/data/sdks/browser-2/#create-your-custom-plugin
* https://pr-842.d19s7xzcva2mw3.amplifyapp.com/data/sdks/browser-2/migration/#simplified-plugin-interface
=> Add docs for Browser SDK plugin.teardown interface

mkdocs.yml
Move:
- Browser V1 to V2 migration doc under Browser V1 (currently under V2)
- Browser JS to V1 migration doc under JS (currently under V1)
- Maintenance Android to Kotlin migration doc under maintenance Android (currently under Kotlin)
- iOS to Swift migration doc under iOS (currently under Swift)
=> AMP-78233 - move migration docs under maintenance SDKs

docs/data/sdks/android/index.md
Descriptions of the two configs should be reversed according to the code 
https://github.com/amplitude/Amplitude-Android/blob/d950578798ca66939fead51e7698c00f9c9f9b00/src/main/java/com/amplitude/api/AmplitudeClient.java#L1531
=> Fix: Android session tracking config

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/browser-2/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/sdk-migration/admonition-link-to-migration-docs.md
As described in https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/pull/845#pullrequestreview-1516861426, add an admonition for each latest SDK with an link to the migration doc
=> AMP-78233-add-links-to-migration-docs

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/ios/index.md, docs/data/sdks/sdk-quickstart.md
- docs: add default events for ios sdk
=> docs: add default events for ios sdk

docs/data/destinations/branch.md, docs/data/destinations/braze.md
We are temporarily disabling braze identify forwarding for syncs where it is not currently enabled.
=> AMP-78975 [event streaming] braze identify forwarding update

docs/data/sources/amazon-s3.md
add more instruction of creating external id for s3 import. Related issue [AMP-79700](https://amplitude.atlassian.net/browse/AMP-79700)
[AMP-79700]: https://amplitude.atlassian.net/browse/AMP-79700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-79700 add more instruction of creating external id for s3 import

docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-react-native/index.md
* Add [compatibility matrix of supported versions of RN, RN CLI, Gradle](https://pr-863.d19s7xzcva2mw3.amplifyapp.com/data/sdks/react-native/#compatibility-matrix) for ReactNative SDK
* Fixed [layout of troubleshooting list](https://pr-863.d19s7xzcva2mw3.amplifyapp.com/data/sdks/react-native/#troubleshooting)
https://pr-863.d19s7xzcva2mw3.amplifyapp.com/data/sdks/react-native/
Related to
*  #856
* https://github.com/amplitude/Amplitude-ReactNative/issues/95
* https://github.com/amplitude/Amplitude-ReactNative/issues/168
=> Amp 80403 add supported versions of rn rn cli for rn sdk releases

requirements.txt
=> fix mkdocs version to 1.4.3 to avoid build failure caused by 1.5.0

docs/data/sdks/ios/index.md
Customer asked about how to use swift to setTrackingOptions in legacy ios sdk.
https://github.com/amplitude/Amplitude-iOS/issues/459
=> feat: add swift example for legacy ios sdk

docs/data/sdks/marketing-analytics-browser/index.md
[AMP-82462](https://amplitude.atlassian.net/browse/AMP-82462)
Update MA SDK Github link to use `v1.x` branch
https://github.com/amplitude/Amplitude-TypeScript/tree/v1.x/packages/marketing-analytics-browser
[AMP-82462]: https://amplitude.atlassian.net/browse/AMP-82462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix MA SDK Github link

docs/data/sources/intercom.md
This project has been delayed so we should not have it in the docs as it's confusing to users
Removed section on integration upgrade that was supposed to happen but hasn't happened yet.
asap
=> remove Intercom source upgrade info for now

docs/data/sources/google-tag-manager-client.md, docs/data/sources/google-tag-manager/index.md, includes/gtm/data-layer-messages-warning.md
* add datalayer message warning to client gtm docs
=> AMP-82699: add datalayer message warning to client gtm docs

docs/experiment/sdks/nodejs-sdk.md, docs/experiment/sdks/python-sdk.md
Experiment Python SDK - auto assignment tracking
=> Experiment Python SDK - auto assignment tracking

docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, docs/data/sdks/typescript-react-native/migration.md
* https://pr-929.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-react-native/
* https://pr-929.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-react-native/migration/
* https://pr-929.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-node/
[AMP-82725](https://amplitude.atlassian.net/browse/AMP-82725) - React Native SDK (TS) doc updates for GA
* `migrateLegacyData` usage
* Location info
* Carrier info
* Fix repo links for `1.x` TS SDKs (RN + Node)
[AMP-82725]: https://amplitude.atlassian.net/browse/AMP-82725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AMP-82725 TS RN doc updates for GA

mkdocs.yml
In Amplify, we redirect `docs.developers.amplitude.com` to `www.docs.developers.amplitude.com`. This causes an issue with our canonical 
tags where the tag uses a base url of `docs.developers.amplitude.com` with the page residing at `www.docs.developers.amplitude.com`.
Google calls this "Alternate page with proper canonical tag" and does not index pages where this is an issue.
This PR updates the base URL of the site to include the `www`, which should cause the canonical tags to match the actual site URL.
=> update site URL to match redirect target URL

docs/experiment/sdks/go-sdk.md
Fix to minor typos in Experiment Go SDK docs
=> fix: minor typos in Experiment Go SDK docs

docs/experiment/sdks/go-sdk.md, docs/experiment/sdks/jvm-sdk.md
Update Experiment server-side SDK JVM dev docs for auto assignment tracking
=> Update Experiment server-side SDK JVM dev docs for auto assignment tracking

docs/experiment/apis/management-api/deployments.md, docs/experiment/apis/management-api/experiments.md, docs/experiment/apis/management-api/flags.md
Fix bugs in examples.
[SKY-3470]: https://amplitude.atlassian.net/browse/SKY-3470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SKY-3470 fix versioning in examples

docs/data/sdks/java/index.md
https://pr-956.d19s7xzcva2mw3.amplifyapp.com/data/sdks/java/#events-with-groups
Java SDK doesn't have `setGroup()` and `groupIdentify()` APIs.
- fix the equivalent of `setGroup()`
- add an equivalent of `groupIdentify()` 
=> fix: Java group and group property docs

docs/data/destinations/kochava-event-streaming-post-installs.md, docs/data/destinations/kochava-event-streaming.md
ticket: https://amplitude.atlassian.net/browse/AMP-83991
- added the explanation the difference between kochava device id and other identifiers.
=> AMP-83991 added explnation for kochava device id

docs/utils/formatguide.md
Fixed a fenced code block that escaped its bounds
=> Format Guide | Fix Guides section

docs/data/sdks/java/index.md
[AMP-84156](https://amplitude.atlassian.net/browse/AMP-84156)
* fix errors in Java SDK group examples
* link to group examples in Java SDK repo
* make Java examples more concise (remove try/catch on JSONObject creation)
[AMP-84156]: https://amplitude.atlassian.net/browse/AMP-84156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix errors in Java SDK group examples, make Java examples more concise

docs/analytics/apis/user-profile-api.md
Thread: https://amplitude.slack.com/archives/C04V216GCF5/p1693989096480709
Feature is ready but doc not updated.. Thus updated related section. Also the response is out of date from my test API, thus update that as well.. 
When do these changes need to be live on the site?  no hard deadline but ASAP
=> AMP-84038 update Profile API doc to include multiple prediction IDs support

docs/experiment/general/data-model.md, docs/experiment/guides/getting-started/create-a-flag.md
=> DDI-435: Experiment update

docs/data/sdks/typescript-react-native/index.md, includes/sdk-android/android-sdk-advertiser-id.md
Replaces Android package used to get advertising Id: `'com.google.android.gms:play-services-ads` -> `com.google.android.gms:play-services-ads-identifier`
[AMP-84238]: https://amplitude.atlassian.net/browse/AMP-84238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-84238 Update Android dependency to get Advertising Id

docs/experiment/sdks/ruby-sdk.md
Update Experiment server-side SDK Ruby dev docs for auto assignment tracking
=> Update Experiment server-side SDK Ruby dev docs for auto assignment tracking

includes/ampli/cli-install-only.md, includes/ampli/cli-install-simple.md, includes/ampli/pages/ampli-overview.md
[AMP-84812](https://amplitude.atlassian.net/browse/AMP-84812)
* added homebrew instructions to Ampli overview page
* code cleanup / reuse
[AMP-84812]: https://amplitude.atlassian.net/browse/AMP-84812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add homebrew instructions to Ampli overview page, code cleanup

docs/data/sdks/browser-2/index.md
Looks like a copy pasta error duplicating info from the page views section. In the context of session tracking this first section removed is confusing.
Now
=> Remove unnecessary statement in Session tracking

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, docs/data/sdks/browser-2/index.md, docs/data/sdks/flutter/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md, docs/data/sdks/java/index.md, docs/data/sdks/javascript/index.md, docs/data/sdks/marketing-analytics-browser/index.md, docs/data/sdks/python/index.md, docs/data/sdks/react-native/index.md, docs/data/sdks/typescript-browser/index.md, docs/data/sdks/typescript-node/index.md, docs/data/sdks/typescript-react-native/index.md, includes/size/browser.md, includes/size/ios.md, includes/size/java.md
Add info on how to check SDK sizes based on https://amplitude.atlassian.net/wiki/spaces/GOV/pages/1787166927/Amplitude+SDK+Non+Functional+Requirement
Example:
=> feat: add SDK sizes

docs/analytics/apis/lookup-tables-api.md, docs/data/sources/lookup-table.md
see https://amplitude.atlassian.net/browse/HC-551
not urgent
=> Updated lookup-table.md with CSV format requirements

docs/data/sdks/browser-2/index.md, docs/data/sdks/typescript-browser/index.md
* filter browser releases to analytics-browser
* Note: I was not able to find a way to filter by both package and version - e.g. `analytics-browser@2`, let me know if you have any suggestions on improving the filters
=> fix: filter browser releases to analytics-browser

docs/robots.txt
added static robots.txt with one page that is excluded from navigation and website search
no urgent
=> AMP-85211 added static robots.txt

docs/data/sdks/ios-swift/index.md
[AMP-82700](https://amplitude.atlassian.net/browse/AMP-82700)
* https://pr-982.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift/#tracking-default-events
* default event tracking for Swift SDK
* Mostly copied from [maintenance iOS docs](https://pr-982.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios/#tracking-default-events), code examples adjusted for Swift SDK
[AMP-82700]: https://amplitude.atlassian.net/browse/AMP-82700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: default event tracking for Swift SDK

docs/data/sdks/ios-swift/index.md
* Removed warning in Swift SDK about Experiment integration not being supported. It is supported now.
=> fix: remove experiment not supported warning

docs/data/sdks/ios-swift/ampli.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios-swift/migration.md, docs/data/sdks/ios/index.md, docs/data/sdks/sdk-quickstart.md, includes/sdk-ios/swift-install-dependencies.md, macros/sdks/ios-install-dependencies.md
* https://pr-984.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift
* https://pr-984.d19s7xzcva2mw3.amplifyapp.com/data/sdks/sdk-quickstart/#ios-beta
* remove cspell comments in iOS docs
* bump AmplitudeSwift version in docs to 0.6.0 (latest)
* added link to Swift SDK examples
* remove Ampli not supported warnings for Swift SDK
=> Fix cspell issues

includes/sdk-troubleshooting-and-debugging/browser.md
Update Browser debugging docs to include solutions for this customer https://amplitude.atlassian.net/browse/AMP-80960
https://pr-959.d19s7xzcva2mw3.amplifyapp.com/data/sdks/browser-2/#events-fired-but-no-network-requests
=> update browser debugging
